(()=>{'use strict';
let CONF=[],CAND=[],LOCAL=[],mode='source',selected='',confirmedMap=new Map(),candidateMap=new Map();
const MY=window.MY||[],IM=window.ANTDEX_IMAGES||{},OV=window.ANTDEX_CATALOG_OVERRIDES||{formal:{},local:[]};
const $=s=>document.querySelector(s),E=v=>(v??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const expandC=o=>({id:o.i,zh:o.z,aliases:o.a,sci:o.s,accepted:o.ac,subfamily:o.f,subfamilyZh:o.fz,genus:o.g,recovery:o.r,imageGrade:o.ig,imageEvidence:o.ie,iisdw:o.is,antden:o.ad,chineseDbImage:o.cd,spid:o.p,antsChina:o.u,antsChinaHistorical:o.uh,antsChinaEvidence:o.ue,china:o.cn,distribution:o.d,habitat:o.h,ecoTags:o.et,nest:o.n,diet:o.di,summary:o.sm,colony:o.co,worker:o.w,soldier:o.so,queen:o.q,male:o.m,identification:o.idn,behavior:o.b,flight:o.fl,temp:o.t,humidity:o.hu,difficulty:o.df,safety:o.sa,taxonomyEvidence:o.te,biologyEvidence:o.be,husbandryEvidence:o.he,conflict:o.cf,missing:o.ms,completeness:o.cp||0,taxonomySource:o.ts,biologySource:o.bs,imageSource:o.ims,legacySource:o.ls,nameSourceLabel:o.nl,nameSourceUrl:o.nu});
const expandA=o=>({id:o.i,zh:o.z,sci:o.s,accepted:o.ac,subfamily:o.f,subfamilyZh:o.fz,genus:o.g,status:o.st,imageEvidence:o.ie,spid:o.p,antsChina:o.u,antsChinaHistorical:o.uh,china:o.cn,missing:o.ms,conflict:o.cf,sharedConflict:o.sc,chineseDbTrace:o.ct,antwiki:o.aw,antweb:o.web,historySource:o.hs,aliases:o.la,distribution:o.ld,habitat:o.lh,ecoTags:o.let,nest:o.ln,diet:o.ldi,summary:o.lsm,worker:o.lw,workerDetail:o.lwd,queen:o.lq,temp:o.lt,humidity:o.lhu,husbandryWarning:o.lhw,measurementSource:o.lmsrc,measurementSourceUrl:o.lmsu,measurementEvidence:o.lmev,legacySource:o.lls,nameSourceLabel:o.lnl,nameSourceUrl:o.lnu,nameNote:o.lnn,oldGrade:o.lgrade,profile:o.lprofile});
async function ungzipB64(b64){const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));return await new Response(new Blob([bin]).stream().pipeThrough(new DecompressionStream('gzip'))).text()}
function applyOverride(x){const o=OV.formal?.[x.sci];if(!o)return x;for(const [k,v] of Object.entries(o)){if(v!==null&&v!==undefined&&v!=='')x[k]=v}return x}
async function loadDb(){const b64=window.ANTDEX_DB_GZ||'';if(!b64)throw new Error('数据库文件未加载');if(!('DecompressionStream'in window))throw new Error('当前浏览器不支持数据库解压，请升级浏览器');const db=JSON.parse(await ungzipB64(b64));CONF=(db.c||[]).map(expandC);CAND=(db.a||[]).map(expandA);let legacy={};if(window.ANTDEX_LEGACY_GZ){try{legacy=JSON.parse(await ungzipB64(window.ANTDEX_LEGACY_GZ))}catch(e){legacy={}}}
for(const c of CAND){const l=legacy[c.sci];if(l){c.aliases=c.aliases||l.a;c.distribution=c.distribution||l.d;c.habitat=c.habitat||l.h;c.ecoTags=c.ecoTags||l.et;c.nest=c.nest||l.n;c.diet=c.diet||l.di;c.summary=c.summary||l.sm;c.worker=c.worker||l.w;c.workerDetail=c.workerDetail||l.wd;c.queen=c.queen||l.q;c.temp=c.temp||l.t;c.humidity=c.humidity||l.hu;c.husbandryWarning=c.husbandryWarning||l.hw;c.measurementSource=c.measurementSource||l.msrc;c.measurementSourceUrl=c.measurementSourceUrl||l.msu;c.measurementEvidence=c.measurementEvidence||l.mev;c.legacySource=c.legacySource||l.ls;c.nameSourceLabel=c.nameSourceLabel||l.nl;c.nameSourceUrl=c.nameSourceUrl||l.nu;c.nameNote=c.nameNote||l.nn;c.oldGrade=c.oldGrade||l.grade;c.profile=c.profile||l.profile;c.antsChina=c.antsChina||l.u;c.antsChinaHistorical=c.antsChinaHistorical||l.uh}applyOverride(c)}
for(const d of CONF){if(d.antsChina&&String(d.recovery||'').startsWith('A2-')){d.antsChinaHistorical=d.antsChinaHistorical||d.antsChina;d.antsChina=null}const l=legacy[d.sci];if(l){d.antsChina=d.antsChina||l.u;d.antsChinaHistorical=d.antsChinaHistorical||l.uh;d.legacySource=d.legacySource||l.ls;d.nameSourceLabel=d.nameSourceLabel||l.nl;d.nameSourceUrl=d.nameSourceUrl||l.nu}applyOverride(d)}
LOCAL=(OV.local||[]).map(x=>({...x,local:true}));db.legacyCount=Object.keys(legacy).length;return db}
const label=x=>x?.zh||x?.sci||'待核';
const cnState=x=>{const v=(x?.china||'').toString();if(/^是/.test(v))return'yes';if(/否|非中国|未见/.test(v))return'no';return'unknown'};
const sourceStatus=x=>{if(x?.local)return'trade';if(x?.antsChina)return'exact';if(x?.antsChinaHistorical)return'historical';if(x?.chineseDbTrace||x?.chineseDbImage)return'trace';if(x?.legacySource||x?.nameSourceLabel)return'legacy';return'none'};
function mergedBySci(sci){const c=candidateMap.get(sci)||{},d=confirmedMap.get(sci)||{};const out={...c};for(const [k,v] of Object.entries(d)){if(v!==null&&v!==undefined&&v!=='')out[k]=v}return applyOverride(out)}
function dataForMode(){if(mode==='source')return CAND.filter(x=>['exact','historical','trace'].includes(sourceStatus(mergedBySci(x.sci))));if(mode==='confirmed')return CONF;if(mode==='local')return LOCAL;return CAND}
function icon(x){const f=x.subfamily||'',v='viewBox="0 0 72 72"';if(f==='Myrmicinae')return`<svg ${v}><path d="M7 36h15M50 36h15"/><ellipse cx="30" cy="36" rx="8" ry="12"/><ellipse cx="44" cy="36" rx="7" ry="10"/></svg>`;if(f==='Myrmeciinae')return`<svg ${v}><circle class="eye" cx="26" cy="25" r="17"/><path class="a" d="M23 45 7 67M31 45 45 67"/></svg>`;if(['Ponerinae','Amblyoponinae','Paraponerinae','Ectatomminae'].includes(f))return`<svg ${v}><ellipse cx="27" cy="38" rx="12" ry="17"/><path class="a" d="M39 39Q57 32 68 16"/></svg>`;return`<svg ${v}><ellipse cx="28" cy="38" rx="12" ry="17"/><circle class="a" cx="57" cy="38" r="9"/></svg>`}
function activeBase(){const q=$('#q')?.value.trim().toLowerCase()||'';if(q){const formal=CAND.map(x=>mergedBySci(x.sci)),all=[...formal,...LOCAL],seen=new Set();return all.filter(x=>{const key=x.local?x.id:x.sci;if(seen.has(key))return false;seen.add(key);const hay=[x.zh,x.aliases,x.sci,x.genus,x.subfamily,x.spid,x.status,x.recovery,x.summary,x.distribution,x.nameSourceLabel].filter(Boolean).join(' ').toLowerCase();return hay.includes(q)})}return dataForMode().map(x=>x.local?x:mergedBySci(x.sci))}
function fillFilters(){const data=dataForMode().map(x=>x.local?x:mergedBySci(x.sci)),sfs=[...new Set(data.map(x=>x.subfamily).filter(Boolean))].sort();$('#sf').innerHTML='<option value="">全部亚科</option>'+sfs.map(v=>`<option value="${E(v)}">${E(v)} · ${E(data.find(x=>x.subfamily===v)?.subfamilyZh||'')}</option>`).join('');const sts=[...new Set(data.map(x=>x.recovery||x.status).filter(Boolean))].sort();$('#status').innerHTML='<option value="">全部恢复状态</option>'+sts.map(v=>`<option value="${E(v)}">${E(v)}</option>`).join('')}
function filtered(){const q=$('#q').value.trim(),sf=$('#sf').value,cn=$('#cn').value,st=$('#status').value;return activeBase().filter(x=>(!sf||x.subfamily===sf)&&(!cn||cnState(x)===cn)&&(!st||(x.recovery||x.status)===st)).sort((a,b)=>{const rank={exact:5,historical:4,trace:3,trade:2,legacy:1,none:0};return rank[sourceStatus(b)]-rank[sourceStatus(a)]||(+!!b.zh-+!!a.zh)||label(a).localeCompare(label(b),'zh-CN')})}
function sourceBadge(x){const s=sourceStatus(x);if(s==='exact')return'<span class="badge srcmain">ants-china原站</span>';if(s==='historical')return'<span class="badge srchist">ants-china历史</span>';if(s==='trace')return'<span class="badge srctrace">Chinese DB痕迹</span>';if(s==='trade')return'<span class="badge srctrade">流通名/待定种</span>';if(s==='legacy')return'<span class="badge srclegacy">旧AntDex资料</span>';return'<span class="badge srcnone">外部候选</span>'}
function list(){const a=filtered(),q=$('#q').value.trim();$('#count').textContent=q?`全库搜索 ${a.length} 条 · 正式种+流通名共同检索`:`显示 ${a.length} / ${dataForMode().length} 条 · ${mode==='source'?'已恢复ants-china证据':mode==='confirmed'?'确认有图':mode==='local'?'流通名/待定种':'全部候选池'}`;$('#list').innerHTML=a.map(x=>{const isOn=(x.local?x.id:x.sci)===selected,d=x.local?false:confirmedMap.has(x.sci);return`<div class="item ${isOn?'on':''}" data-key="${E(x.local?x.id:x.sci)}" data-local="${x.local?'1':'0'}"><div class="ico">${icon(x)}</div><div><div class="nm">${E(label(x))}</div><div class="sci">${E(x.sci)}</div><div class="badges">${sourceBadge(x)}${d?'<span class="badge deep">确认有图</span>':''}${/^是/.test(x.china||'')?'<span class="badge cn">中国</span>':''}${x.spid?`<span class="badge idb">ID ${E(x.spid)}</span>`:''}</div></div></div>`}).join('');document.querySelectorAll('.item').forEach(el=>el.onclick=()=>{selected=el.dataset.key;list();center();$('.center')?.scrollTo({top:0,behavior:'smooth'})})}
function sourceLink(n,u,cls=''){return u?`<a class="${cls}" target="_blank" rel="noopener" href="${E(u)}">${E(n)}</a>`:''}
function picture(x){if(x.local)return`<div class="photo"><div class="ph"><strong>待定种不使用正式种照片代替</strong><br>确认种级身份后再绑定图片。</div><span class="imgev pending">待定种</span></div>`;const m=IM[x.id];if(m?.file)return`<div class="photo"><img src="${E(m.file)}" alt="${E(label(x))}"><span class="imgev">本地图片</span></div><div class="credit">${E([m.source,m.photographer,m.license].filter(Boolean).join(' · '))}</div>`;const d=confirmedMap.get(x.sci),msg=d?'已有可追溯图片证据，本地图片仍在补齐':'当前未确认本地图片';return`<div class="photo"><div class="ph"><strong>${E(msg)}</strong>${d?.imageEvidence?'<br>'+E(d.imageEvidence):'<br>不使用近缘种照片冒充。'}</div><span class="imgev ${d?'':'pending'}">${d?'有图证据':'待补图'}</span></div>`}
function metaRow(k,v){return v?`<b>${E(k)}</b><span>${E(v)}</span>`:''}
function formalProvenance(x){const s=sourceStatus(x);if(s==='exact')return`<div class="card wide sourcecard exact"><h3>主来源：ants-china / Chinese Ant Database <span class="ev">原站物种页已恢复</span></h3><p>已恢复该物种对应的 ants-china 原站页面${x.spid?'（ID '+E(x.spid)+'）':''}。其他数据库仅用于补空字段。</p><div class="links">${sourceLink('ants-china 原站页',x.antsChina,'sourceok')}</div></div>`;if(s==='historical')return`<div class="card wide sourcecard historical"><h3>ants-china 历史来源痕迹</h3><p>已保存历史名称/页面来源，但证据不足以全部升级成精确原站物种页。</p><div class="links">${sourceLink('历史 ants-china 链接',x.antsChinaHistorical,'sourceok')}</div></div>`;if(s==='trace')return`<div class="card wide sourcecard trace"><h3>Chinese Ant Database 引用痕迹</h3><p>公开页面证明该物种曾与 Chinese Ant Database 关联，但原站数字ID或完整页面尚未恢复。</p></div>`;if(s==='legacy')return`<div class="card wide sourcecard supplemental"><h3>旧 AntDex 已整理资料</h3><p>本条保存了旧 AntDex 的中文名/自然史等资料，但当前没有足够证据把这些字段全部标成 ants-china 原站内容。</p></div>`;return`<div class="card wide sourcecard supplemental"><h3>外部候选池条目</h3><p>当前没有可验证的 ants-china 原站痕迹。保留本条是为了做差集与后续恢复，不再把它包装成 ants-china 原始数据。</p></div>`}
function supplementaryLinks(x){const main=[sourceLink('ants-china 原站',x.antsChina,'sourceok'),sourceLink('ants-china 历史链接',x.antsChinaHistorical,'sourceok'),sourceLink('IISDW',x.iisdw),sourceLink('AntDen',x.antden)].join('');const aw=x.antwiki||('https://www.antwiki.org/wiki/'+x.sci.replaceAll(' ','_')),antweb=x.antweb||('https://www.antweb.org/description.do?genus='+encodeURIComponent(x.genus||'')+'&species='+encodeURIComponent(x.sci.split(' ')[1]||''));const supp=[sourceLink('AntWiki（补充）',aw),sourceLink('AntWeb（补充）',antweb),sourceLink('旧名称来源',x.nameSourceUrl)].join('');const override=(x.supplementSources||[]).map(([n,u])=>sourceLink(n,u)).join('');return{main,supp:supp+override}}
function findLocal(key){return LOCAL.find(x=>x.id===key)}
function localCenter(x){const src=(x.sourceUrls||[]).map(([n,u])=>sourceLink(n,u)).join('');const rel=(x.related||[]).map(s=>`<button class="relbtn" data-rel="${E(s)}">${E(label(mergedBySci(s)))} · ${E(s)}</button>`).join('');$('#hero').innerHTML=`<div class="hg"><div><div class="k">LOCAL / TRADE NAME INDEX</div><h1>${E(x.zh)}</h1><div class="latin">${E(x.sci)}</div><div class="alias">别名：${E(x.aliases||'')}</div><div class="tax">${E(x.subfamilyZh)} · ${E(x.subfamily)} · ${E(x.genus)} · ${E(x.status)}</div><div class="acts">${src||'<span class="muted">当前无原站来源</span>'}</div></div><div>${picture(x)}</div></div>`;$('#content').innerHTML=`<div class="grid"><div class="card wide sourcecard local"><h3>为什么单独建这一层</h3><p>${E(x.summary)}</p></div><div class="card wide"><h3>鉴定状态</h3><p>${E(x.identification||'种级身份待核。')}</p></div><div class="card wide"><h3>相关正式种</h3><div class="related">${rel||'<span class="muted">暂无关联正式种</span>'}</div></div><div class="card wide"><h3>来源说明</h3><p>这是流通名/地域型索引，不等同于 ants-china 正式物种页，也不强行映射为任何正式种。</p><div class="links">${src}</div></div></div>`;document.querySelectorAll('.relbtn').forEach(b=>b.onclick=()=>{selected=b.dataset.rel;mode='all';syncMode(false);center()})}
function center(){const local=findLocal(selected);if(local)return localCenter(local);let x=mergedBySci(selected);if(!x?.sci){const first=filtered()[0];if(!first)return;selected=first.local?first.id:first.sci;return center()}const links=supplementaryLinks(x),d=confirmedMap.get(x.sci);$('#hero').innerHTML=`<div class="hg"><div><div class="k">${d?'CONFIRMED IMAGE SPECIES':'RECOVERY CANDIDATE'} · ${E(x.recovery||x.status||'')}</div><h1>${E(label(x))}</h1><div class="latin">${E(x.sci)}</div>${x.aliases?`<div class="alias">别名：${E(x.aliases)}</div>`:''}<div class="tax">${E(x.subfamilyZh||x.subfamily||'')} · ${E(x.subfamily||'')} · ${E(x.genus||'')}${x.spid?` · ants-china ID ${E(x.spid)}`:''}</div><div class="acts">${links.main||'<span class="muted">ants-china 原站链接尚未恢复</span>'}</div></div><div>${picture(x)}</div></div>`;let cards=formalProvenance(x);const core=[metaRow('工蚁体长',x.worker),metaRow('兵蚁体长',x.soldier),metaRow('蚁后体长',x.queen),metaRow('雄蚁体长',x.male),metaRow('中国记录',x.china),metaRow('资料完整度',x.completeness?x.completeness+'%':''),metaRow('饲养温度',x.temp),metaRow('饲养湿度',x.humidity)].join('');if(x.summary)cards+=`<div class="card wide verified"><h3>物种概览</h3><p>${E(x.summary)}</p></div>`;cards+=`<div class="card"><h3>核心参数</h3><div class="meta">${core||'<span class="muted">核心参数待补</span>'}</div></div>`;cards+=`<div class="card"><h3>分布与生境</h3><div class="meta">${metaRow('全球分布',x.distribution)}${metaRow('生境',x.habitat)}${metaRow('筑巢',x.nest)}${metaRow('食性',x.diet)}</div></div>`;if(x.identification)cards+=`<div class="card wide"><h3>形态与鉴别</h3><p>${E(x.identification)}</p></div>`;if(x.behavior||x.colony||x.flight)cards+=`<div class="card wide"><h3>行为、群落与婚飞</h3><p>${E([x.behavior,x.colony,x.flight&&('婚飞：'+x.flight)].filter(Boolean).join('；'))}</p></div>`;if(x.imageEvidence)cards+=`<div class="card"><h3>图片证据</h3><p>${E(x.imageEvidence)}</p></div>`;if(x.conflict||x.sharedConflict)cards+=`<div class="card wide"><h3>冲突 / 复核</h3><div class="warn">${E([x.sharedConflict,x.conflict].filter(Boolean).join('；'))}</div></div>`;if(x.missing)cards+=`<div class="card wide"><h3>仍待补充</h3><div class="missing">${E(x.missing)}</div></div>`;cards+=`<div class="card wide"><h3>补充数据库（不是主来源）</h3><div class="links">${links.supp}</div></div>`;$('#content').innerHTML=`<div class="grid">${cards}</div>`}
function renderMy(){const byId=new Map(CAND.map(x=>[x.id,x]));$('#mc').textContent=`${MY.length} 条`;$('#my').innerHTML=MY.map(m=>{const x=m.m?byId.get(m.m):null;return`<div class="mi" data-sci="${E(x?.sci||'')}"><div class="mr"><b>${E(m.l)}</b><span class="days">${E(m.d)}d</span></div><div class="st">${E(m.st)}${x?' · '+E(x.sci):''}</div></div>`}).join('');document.querySelectorAll('.mi').forEach(el=>{if(el.dataset.sci)el.onclick=()=>{selected=el.dataset.sci;mode='all';$('#q').value='';syncMode()}})}
function syncMode(recenter=true){document.querySelectorAll('.modebtn').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));fillFilters();if(!$('#q').value.trim()){const d=dataForMode();if(!d.some(x=>(x.local?x.id:x.sci)===selected))selected=d[0]?(d[0].local?d[0].id:d[0].sci):''}list();if(recenter)center()}
function auditStats(){const all=CAND.map(x=>mergedBySci(x.sci)),counts={exact:0,historical:0,trace:0,legacy:0,none:0};all.forEach(x=>counts[sourceStatus(x)]++);const cn=all.filter(x=>cnState(x)==='yes'),cnNoZh=cn.filter(x=>!x.zh).length;$('#sourceStat').innerHTML=`精确原站 ${counts.exact} · 历史/引用痕迹 ${counts.historical+counts.trace}<br>旧AntDex但原站未确证 ${counts.legacy} · 外部候选 ${counts.none}<br>中国记录 ${cn.length} · 仍缺中文名 ${cnNoZh}`}
async function boot(){try{const db=await loadDb();confirmedMap=new Map(CONF.map(x=>[x.sci,x]));candidateMap=new Map(CAND.map(x=>[x.sci,x]));selected=dataForMode()[0]?.sci||'';$('#confirmedStat').textContent=CONF.length;$('#candidateStat').textContent=CAND.length;$('#dataVersion').textContent='2026-08-16';document.querySelectorAll('.modebtn').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$('#q').value='';syncMode()});['#q','#sf','#cn','#status'].forEach(s=>$(s).addEventListener(s==='#q'?'input':'change',()=>{list();const first=filtered()[0];if(first){selected=first.local?first.id:first.sci;center()}}));fillFilters();list();center();renderMy();auditStats()}catch(err){$('#hero').innerHTML=`<div class="loading">数据库加载失败：${E(err.message||err)}</div>`;$('#content').innerHTML=''}}boot();
})();
