(()=>{
'use strict';
const S=window.S||[], MY=window.MY||[], RX=window.ANTDEX_RICH||{};
if(!S.length)return;
let id=S[0].i, mode=0;
const $=s=>document.querySelector(s);
const E=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const SF={Formicinae:'蚁亚科',Myrmicinae:'切叶蚁亚科',Ponerinae:'猛蚁亚科',Ectatomminae:'突蚁亚科',Amblyoponinae:'钝猛蚁亚科',Paraponerinae:'近猛蚁亚科',Dolichoderinae:'臭蚁亚科',Myrmeciinae:'犬蚁亚科',Dorylinae:'行军蚁亚科',Pseudomyrmecinae:'伪切叶蚁亚科',Proceratiinae:'卷尾猛蚁亚科',Leptanillinae:'细蚁亚科'};
const liveZh={};
const badValues=new Set(['待核','待物种级核实','待核原始描述','暂无可靠总长数据','暂无可靠总长','暂无可靠总长数据 / 待核原始描述']);
const good=v=>!!v&&!badValues.has(String(v).trim());
const rich=x=>RX[x.s]||{};
const label=x=>x.z||liveZh[x.s]||x.s;
const hasZh=x=>!!(x.z||liveZh[x.s]);
const isDeep=x=>!!(x.p||Object.keys(rich(x)).length);
function core(x,k){const r=rich(x);if(good(x[k]))return x[k];if(k==='w'&&good(r.worker))return r.worker;if(k==='q'&&good(r.queen))return r.queen;if(k==='t'&&good(r.temperature))return r.temperature;if(k==='hu'&&good(r.humidity))return r.humidity;return '待核'}
function regions(x){const r=rich(x),out=new Set(x.reg||[]);(r.regions||[]).forEach(v=>out.add(v));return [...out]}
function habitat(x){const r=rich(x);return good(x.hab)?x.hab:(r.habitat||'待物种级核实')}
function nest(x){const r=rich(x);return good(x.ne)?x.ne:(r.nest||'待物种级核实')}
function diet(x){const r=rich(x);return good(x.di)?x.di:(r.diet||'待物种级核实')}
function summary(x){const r=rich(x);return r.summary||x.sm||'已进入 AntDex 图鉴收录层。当前仅展示已入库并可追溯的物种级信息；未核实参数不使用近缘种代填。'}
function opts(el,a,first){$(el).innerHTML='<option value="">'+first+'</option>'+a.map(v=>'<option>'+E(v)+'</option>').join('')}
opts('#sf',[...new Set(S.map(x=>x.f+' · '+(x.fz||SF[x.f]||'')))].sort(),'全部亚科');
opts('#reg',['亚洲','欧洲','非洲','北美洲','南美洲','大洋洲','南极洲','中国'],'全部地区');
opts('#level',['深度资料','图鉴收录'],'全部资料级别');
opts('#cnf',['有中文名','待补中文名'],'全部中文名状态');
function icon(t){let v='viewBox="0 0 72 72"';if(t==='two_node_waist')return`<svg ${v}><path d="M7 36h15M50 36h15"/><ellipse cx="30" cy="36" rx="8" ry="12"/><ellipse cx="44" cy="36" rx="7" ry="10"/></svg>`;if(t==='eye_mandibles')return`<svg ${v}><circle class="eye" cx="26" cy="25" r="17"/><path class="a" d="M23 45 7 67M31 45 45 67"/></svg>`;if(t==='propodeal_spines')return`<svg ${v}><path d="M10 51Q36 44 62 51L57 35H15Z"/><path class="a" d="M18 38 9 10M28 35 24 8M45 35 48 8M54 38 64 10"/></svg>`;if(t==='node_sting'||t==='large_sting')return`<svg ${v}><ellipse cx="27" cy="38" rx="12" ry="17"/><path class="a" d="M39 39Q57 32 68 16"/></svg>`;if(t==='long_mandibles'||t==='sickle_mandibles')return`<svg ${v}><path d="M21 18Q36 10 51 18v27Q36 56 21 45Z"/><path class="a" d="M28 44 8 66M44 44 64 66"/></svg>`;if(t==='curled_gaster')return`<svg ${v}><path class="a" d="M12 30Q30 8 52 19Q68 31 57 49Q48 63 31 56Q22 52 24 42Q27 34 38 36Q44 38 41 46"/></svg>`;return`<svg ${v}><ellipse cx="28" cy="38" rx="12" ry="17"/><circle class="a" cx="57" cy="38" r="9"/></svg>`}
function filtered(){const q=$('#q').value.trim().toLowerCase(),sf=$('#sf').value,r=$('#reg').value,l=$('#level').value,c=$('#cnf').value;return S.filter(x=>{const rr=rich(x),hay=[x.z,liveZh[x.s],x.s,x.g,...(x.a||[]),rr.summary,rr.distribution].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!sf||sf.startsWith(x.f+' ·'))&&(!r||regions(x).includes(r))&&(!l||(l==='深度资料'?isDeep(x):!isDeep(x)))&&(!c||(c==='有中文名'?hasZh(x):!hasZh(x)))}).sort((a,b)=>(hasZh(b)-hasZh(a))||(isDeep(b)-isDeep(a))||label(a).localeCompare(label(b),'zh-CN'))}
function list(){const a=filtered();$('#count').textContent=`显示 ${a.length} / ${S.length} 条 · 中文名优先`;$('#list').innerHTML=a.map(x=>`<div class="item ${x.i===id?'on':''}" data-i="${E(x.i)}"><div class="ico">${icon(x.ic)}</div><div><div class="nm">${E(label(x))}</div>${hasZh(x)?`<div class="sci">${E(x.s)}</div>`:''}<div class="badges"><span class="badge ${isDeep(x)?'deep':''}">${isDeep(x)?'深度资料':'图鉴收录'}</span>${hasZh(x)?'<span class="badge cn">中文名</span>':''}<span class="badge">${E(x.g)}</span></div></div></div>`).join('');document.querySelectorAll('.item').forEach(e=>e.onclick=()=>{id=e.dataset.i;mode=0;list();center();$('.center')?.scrollTo({top:0,behavior:'smooth'})})}
function googleLink(url){return 'https://translate.google.com/translate?sl=auto&tl=zh-CN&u='+encodeURIComponent(url)}
function sourceLinks(x){const r=rich(x),aw='https://www.antwiki.org/wiki/'+x.s.replaceAll(' ','_'),wp='https://en.wikipedia.org/wiki/'+x.s.replaceAll(' ','_'),zw='https://zh.wikipedia.org/w/index.php?search='+encodeURIComponent(x.s),antweb='https://www.antweb.org/description.do?subfamily='+encodeURIComponent(x.f)+'&genus='+encodeURIComponent(x.g)+'&species='+encodeURIComponent(x.s.split(' ')[1]||'');const verified=(r.sources||[]).map(a=>`<a class="sourceok" target="_blank" rel="noopener" href="${a[1]}">${E(a[0])} · ${E(a[2]||'来源')}</a>`).join('');return`<div class="links">${verified}<a target="_blank" rel="noopener" href="${aw}">AntWiki 物种页</a><a target="_blank" rel="noopener" href="${antweb}">AntWeb 物种页</a>${x.ac?`<a target="_blank" rel="noopener" href="${x.ac}">ants-china</a>`:''}<a target="_blank" rel="noopener" href="${zw}">中文 Wikipedia</a><a target="_blank" rel="noopener" href="${wp}">英文 Wikipedia</a><a target="_blank" rel="noopener" href="${googleLink(aw)}">Google翻译 AntWiki</a></div>`}
function richCard(x){const r=rich(x);if(!Object.keys(r).length)return'';const fs=[['分布',r.distribution],['形态与鉴别',r.identification],['生态/群落',r.ecology],['分类与命名',r.nomenclature]].filter(v=>v[1]);return`<div class="card wide verified"><h3>AntDex 已整理物种资料 <span class="ev">${E(r.status||'已核')}</span></h3>${r.summary?`<p class="detaillead">${E(r.summary)}</p>`:''}<div class="richfacts">${fs.map(v=>`<div><b>${E(v[0])}</b><p>${E(v[1])}</p></div>`).join('')}</div></div>`}
async function natural(x,slot){const b=document.getElementById(slot);if(!b)return;try{const q=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrsearch:'"'+x.s+'"',gsrnamespace:'6',gsrlimit:'24',prop:'imageinfo',iiprop:'url|extmetadata',iiurlwidth:'1200'}),resp=await fetch('https://commons.wikimedia.org/w/api.php?'+q),d=await resp.json(),pages=Object.values(d.query?.pages||{}),deny=/casent|antweb|specimen|holotype|paratype|head|profile|dorsal|label|map|plate|museum|drawing|illustration/i,g=x.g.toLowerCase(),sp=(x.s.split(' ')[1]||'').toLowerCase();let z=pages.find(y=>{const ii=y.imageinfo?.[0],t=(y.title||'').toLowerCase();return ii&&!deny.test(t)&&t.includes(g)&&(!sp||t.includes(sp))});if(!z)z=pages.find(y=>{const ii=y.imageinfo?.[0],t=(y.title||'').toLowerCase();return ii&&!deny.test(t)&&t.includes(g)});if(z){const ii=z.imageinfo[0],m=ii.extmetadata||{},artist=(m.Artist?.value||'').replace(/<[^>]+>/g,'').trim(),license=m.LicenseShortName?.value||m.License?.value||'开放授权';b.innerHTML=`<img src="${ii.thumburl||ii.url}" alt="${E(label(x))}"><div class="credit">Wikimedia Commons · ${E(license)}${artist?' · '+E(artist):''}</div>`;return}}catch(e){}b.innerHTML=`<div class="ph"><b>${E(habitat(x)==='待物种级核实'?'自然生态照片待补':habitat(x))}</b><br><br>未匹配到可确认物种且开放授权的自然/生态照；不使用标本图冒充实景照。</div>`}
async function fetchWiki(api,title,search=false,ms=5500){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),ms);try{let q;if(search)q=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrsearch:'"'+title+'"',gsrnamespace:'0',gsrlimit:'6',prop:'extracts',exintro:'1',explaintext:'1'});else q=new URLSearchParams({action:'query',format:'json',origin:'*',prop:'extracts',exintro:'1',explaintext:'1',redirects:'1',titles:title});const r=await fetch(api+'?'+q,{signal:ctl.signal,cache:'force-cache'});if(!r.ok)return'';const d=await r.json(),p=Object.values(d.query?.pages||{}).find(v=>v.extract&&v.missing===undefined);return p?.extract||''}catch(e){return''}finally{clearTimeout(tm)}}
function isZh(t){const n=(t.match(/[\u3400-\u9fff]/g)||[]).length;return n>Math.max(8,t.length*.08)}
async function translateZh(t){if(!t||isZh(t))return t;try{const s=t.slice(0,1200),u='https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=zh-CN&dt=t&q='+encodeURIComponent(s),r=await fetch(u),d=await r.json(),z=(d[0]||[]).map(a=>a[0]).join('');return z||''}catch(e){return''}}
async function publicSupplement(x){const box=$('#sourceDetail');if(!box)return;const r=rich(x);box.innerHTML=`<h3>${Object.keys(r).length?'补充公开来源':'公开来源补充阅读'}</h3><div class="source-note">核心参数只读取 AntDex 已入库字段。这里的网络资料只作补充阅读，网络失败不会改变核心参数。</div><div id="liveSources"><p class="muted">正在检查 Wikipedia 可直接读取的物种级摘要…</p></div>`;const live=$('#liveSources');let zh=await fetchWiki('https://zh.wikipedia.org/w/api.php',x.s);if(!zh)zh=await fetchWiki('https://zh.wikipedia.org/w/api.php',x.s,true);if(zh){live.innerHTML=`<div class="srcblock"><div class="srctitle srcname">中文 Wikipedia <a target="_blank" rel="noopener" href="https://zh.wikipedia.org/w/index.php?search=${encodeURIComponent(x.s)}">查看原文</a></div><p>${E(zh.slice(0,1100))}${zh.length>1100?'…':''}</p></div>`;return}const en=await fetchWiki('https://en.wikipedia.org/w/api.php',x.s);if(en){const tr=await translateZh(en);live.innerHTML=`<div class="srcblock"><div class="srctitle srcname">英文 Wikipedia ${tr?'<span class="machine">机器翻译</span>':'<span class="machine">英文原文</span>'} <a target="_blank" rel="noopener" href="https://en.wikipedia.org/wiki/${encodeURIComponent(x.s.replaceAll(' ','_'))}">查看原文</a></div><p>${E((tr||en).slice(0,1100))}${(tr||en).length>1100?'…':''}</p>${tr?'<div class="source-note">机器翻译仅用于辅助阅读，事实证据仍以原文为准。</div>':''}</div>`;return}live.innerHTML=`<div class="sourcefail">未找到可直接读取的 Wikipedia 物种摘要。这不代表公开资料不存在；AntWiki、AntWeb 与其他已登记来源仍可通过下方“来源”打开。AntDex 不会因为本次网络读取失败而清空已入库资料。</div>`}
function deepFindImages(obj,out=[]){if(!obj)return out;if(Array.isArray(obj)){obj.forEach(v=>deepFindImages(v,out));return out}if(typeof obj==='object'){const shot=(obj.shot_type||obj.shotType||obj.shottype||'').toString().toLowerCase(),urls=obj.urls||obj.url||obj.medium||obj.high||obj.thumbnail;if(shot&&urls)out.push(obj);Object.values(obj).forEach(v=>{if(v&&typeof v==='object')deepFindImages(v,out)});}return out}
function imgUrl(v){if(!v)return'';if(typeof v.urls==='string')return v.urls;if(v.urls&&typeof v.urls==='object')return v.urls.medium||v.urls.high||v.urls.thumbnail||v.urls.low||Object.values(v.urls).find(x=>typeof x==='string')||'';return v.medium||v.high||v.thumbnail||(typeof v.url==='string'?v.url:'')}
function shot(v){return (v.shot_type||v.shotType||v.shottype||'').toString().toLowerCase()}
function specimen(v){return v.specimen_code||v.specimenCode||v.code||v.specimen?.code||''}
function photographer(v){return v.photographer||v.artist||v.copyright||v.image_author||v.imageAuthor||''}
async function antweb(x){const b=$('#gal');if(!b)return;const parts=x.s.split(' '),species=parts[1]||'',subspecies=parts.slice(2).join(' ');const q=new URLSearchParams({genus:x.g,species,limit:'80'});if(subspecies)q.set('subspecies',subspecies);try{const r=await fetch('https://www.antweb.org/v3.1/taxaImages?'+q,{cache:'force-cache'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();let a=[];if(Array.isArray(d.images))a=d.images;else if(Array.isArray(d))a=d;else a=deepFindImages(d,[]);const uniq=[];const seen=new Set();for(const v of a){const u=imgUrl(v),s=shot(v);if(!u||!s)continue;const k=s+'|'+u;if(!seen.has(k)){seen.add(k);uniq.push(v)}}function card(t,n){const y=uniq.find(v=>shot(v)===t),u=imgUrl(y),code=specimen(y),who=photographer(y),src=code?'https://www.antweb.org/specimen.do?code='+encodeURIComponent(code):'https://www.antweb.org/';return`<div class="gcard">${u?`<a target="_blank" rel="noopener" href="${src}"><img loading="lazy" src="${u}" alt="${E(n+' '+x.s)}"></a>`:`<div class="empty">${E(n)}<br>暂无图像</div>`}<div class="glabel">${E(n)} · AntWeb${code?' · '+E(code):''}${who?' · '+E(who):''}</div></div>`}b.innerHTML=card('h','HEAD 头部')+card('p','PROFILE 侧面')+card('d','DORSAL 背面')}catch(e){b.innerHTML='<div class="empty">本次未能读取 AntWeb 标本照。可从下方来源直接打开 AntWeb 物种页；其他资料不受影响。</div>'}}
function overview(x){const rr=rich(x),rg=regions(x);$('#hero').innerHTML=`<div class="hg"><div><div class="k">ANTDEX · ${E(x.f+' · '+(x.fz||SF[x.f]||''))} · ${isDeep(x)?'深度资料':'图鉴收录'}</div><h1>${E(label(x))}</h1>${hasZh(x)?`<div class="latin">${E(x.s)}</div>`:''}${x.a?.length?`<div class="alias">别名：${E(x.a.join(' / '))}</div>`:''}<div class="tax">Formicidae 蚁科 → ${E(x.f)} → ${E(x.g)} → <i>${E(x.s)}</i></div><div class="acts"><button class="dark" id="full">查看完整详情 →</button></div></div><div><div class="photo" id="pic"><div class="ph">正在匹配自然 / 生态照片…</div></div></div></div>`;$('#content').innerHTML=`<div class="grid"><div class="card"><h3>物种概览</h3><p>${E(summary(x))}</p></div><div class="card"><h3>分类与名称</h3><div class="meta"><b>亚科</b><span>${E(x.f+' · '+(x.fz||SF[x.f]||''))}</span><b>属</b><span>${E(x.g)}</span><b>中文名状态</b><span>${hasZh(x)?E(x.cn||'已有中文名'):'待补中文名'}</span><b>地区</b><span>${E(rg.join(' / ')||rr.distribution||'待物种级核实')}</span></div></div><div class="card"><h3>体型</h3><div class="meta"><b>工蚁</b><span>${E(core(x,'w'))}</span><b>蚁后</b><span>${E(core(x,'q'))}</span></div></div><div class="card"><h3>饲养环境</h3><div class="meta"><b>温度</b><span>${E(core(x,'t'))}</span><b>湿度/保湿</b><span>${E(core(x,'hu'))}</span></div></div><div class="card"><h3>生境与巢址</h3><div class="meta"><b>生境</b><span>${E(habitat(x))}</span><b>巢址</b><span>${E(nest(x))}</span></div></div><div class="card"><h3>食性</h3><p>${E(diet(x))}</p></div><div class="card wide"><h3>来源</h3>${sourceLinks(x)}</div></div>`;$('#full').onclick=()=>{mode=1;center();$('.center')?.scrollTo({top:0,behavior:'smooth'})};natural(x,'pic')}
function full(x){$('#hero').innerHTML=`<div class="fullbar"><button class="ghost" id="back">← 返回物种概览</button><b>${E(label(x))}</b><i>${E(x.s)}</i></div>`;$('#content').innerHTML=`<div class="grid"><div class="card"><h3>分类信息</h3><div class="meta"><b>学名</b><span><i>${E(x.s)}</i></span><b>属</b><span>${E(x.g)}</span><b>亚科</b><span>${E(x.f+' · '+(x.fz||SF[x.f]||''))}</span><b>等级</b><span>${E(x.r)}</span></div></div><div class="card"><h3>核心参数</h3><div class="meta"><b>工蚁</b><span>${E(core(x,'w'))}</span><b>蚁后</b><span>${E(core(x,'q'))}</span><b>温度</b><span>${E(core(x,'t'))}</span><b>湿度</b><span>${E(core(x,'hu'))}</span></div><div class="source-note">核心参数与概览使用同一套 AntDex 入库字段；公开网页实时读取只用于补充阅读，不会覆盖核心参数。</div></div>${richCard(x)}<div class="card wide"><div class="photo" id="fp"><div class="ph">加载自然 / 生态照片…</div></div></div><div class="card wide" id="sourceDetail"><h3>公开来源补充阅读</h3><p class="muted">准备中…</p></div><div class="card wide"><h3>AntWeb 标准标本照</h3><p style="margin-bottom:10px">按 AntWeb Taxa Images API 查询 HEAD / PROFILE / DORSAL；图片保留 AntWeb 来源、标本编号及可用摄影者信息。</p><div class="gallery" id="gal"><div class="empty">加载中…</div></div></div><div class="card wide"><h3>来源</h3>${sourceLinks(x)}</div></div>`;$('#back').onclick=()=>{mode=0;center()};natural(x,'fp');publicSupplement(x);antweb(x)}
function center(){const x=S.find(v=>v.i===id)||S[0];mode?full(x):overview(x)}
function my(){if(!$('#my'))return;$('#mc').textContent=MY.length+' 条';$('#my').innerHTML=MY.map(m=>`<div class="mi" data-m="${E(m.m||'')}"><div class="mr"><b>${E(m.l)}</b><span class="days">${E(m.d)}天</span></div><div class="st">${E(m.st)}</div></div>`).join('');document.querySelectorAll('.mi').forEach(e=>e.onclick=()=>{if(e.dataset.m&&S.some(x=>x.i===e.dataset.m)){id=e.dataset.m;mode=0;list();center()}})}
async function zhfill(){const a=S.filter(x=>!x.z&&!liveZh[x.s]);for(let i=0;i<a.length;i+=45){try{const c=a.slice(i,i+45),q=new URLSearchParams({action:'wbgetentities',format:'json',origin:'*',sites:'enwiki',titles:c.map(x=>x.s).join('|'),props:'labels|sitelinks',languages:'zh'}),r=await fetch('https://www.wikidata.org/w/api.php?'+q),d=await r.json();for(const e of Object.values(d.entities||{})){const en=e.sitelinks?.enwiki?.title,z=e.labels?.zh?.value;if(en&&z&&/[\u3400-\u9fff]/.test(z))liveZh[en]=z}}catch(e){}}list();center()}
['q','sf','reg','level','cnf'].forEach(k=>$('#'+k).addEventListener(k==='q'?'input':'change',list));
list();center();my();setTimeout(zhfill,500);
})();
