(()=>{'use strict';
let CONF=[],CAND=[],mode='confirmed',selected='',confirmedMap=new Map(),candidateMap=new Map();
const MY=window.MY||[],IM=window.ANTDEX_IMAGES||{};
const $=s=>document.querySelector(s),E=v=>(v??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const expandC=o=>({id:o.i,zh:o.z,aliases:o.a,sci:o.s,accepted:o.ac,subfamily:o.f,subfamilyZh:o.fz,genus:o.g,recovery:o.r,imageGrade:o.ig,imageEvidence:o.ie,iisdw:o.is,antden:o.ad,chineseDbImage:o.cd,spid:o.p,antsChina:o.u,antsChinaEvidence:o.ue,china:o.cn,distribution:o.d,habitat:o.h,ecoTags:o.et,nest:o.n,diet:o.di,summary:o.sm,colony:o.co,worker:o.w,soldier:o.so,queen:o.q,male:o.m,identification:o.idn,behavior:o.b,flight:o.fl,temp:o.t,humidity:o.hu,difficulty:o.df,safety:o.sa,taxonomyEvidence:o.te,biologyEvidence:o.be,husbandryEvidence:o.he,conflict:o.cf,missing:o.ms,completeness:o.cp||0});
const expandA=o=>({id:o.i,zh:o.z,sci:o.s,subfamily:o.f,subfamilyZh:o.fz,genus:o.g,status:o.st,imageEvidence:o.ie,spid:o.p,china:o.cn,missing:o.ms,conflict:o.cf,sharedConflict:o.sc,chineseDbTrace:o.ct,antsChina:o.u});
async function loadDb(){const b64=window.ANTDEX_DB_GZ||'';if(!b64)throw new Error('数据库文件未加载');const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if(!('DecompressionStream'in window))throw new Error('当前浏览器不支持数据库解压，请升级浏览器');const text=await new Response(new Blob([bin]).stream().pipeThrough(new DecompressionStream('gzip'))).text();const db=JSON.parse(text);CONF=(db.c||[]).map(expandC);CAND=(db.a||[]).map(expandA);return db}
const active=()=>mode==='confirmed'?CONF:CAND,label=x=>x?.zh||x?.sci||'待核';
const cnState=x=>{const v=(x?.china||'').toString();if(/^是/.test(v))return'yes';if(/否|非中国|未见/.test(v))return'no';return'unknown'};
function icon(x){const f=x.subfamily||'';const v='viewBox="0 0 72 72"';if(f==='Myrmicinae')return`<svg ${v}><path d="M7 36h15M50 36h15"/><ellipse cx="30" cy="36" rx="8" ry="12"/><ellipse cx="44" cy="36" rx="7" ry="10"/></svg>`;if(f==='Myrmeciinae')return`<svg ${v}><circle class="eye" cx="26" cy="25" r="17"/><path class="a" d="M23 45 7 67M31 45 45 67"/></svg>`;if(['Ponerinae','Amblyoponinae','Paraponerinae','Ectatomminae'].includes(f))return`<svg ${v}><ellipse cx="27" cy="38" rx="12" ry="17"/><path class="a" d="M39 39Q57 32 68 16"/></svg>`;return`<svg ${v}><ellipse cx="28" cy="38" rx="12" ry="17"/><circle class="a" cx="57" cy="38" r="9"/></svg>`}
function fillFilters(){const data=active(),sfs=[...new Set(data.map(x=>x.subfamily).filter(Boolean))].sort();$('#sf').innerHTML='<option value="">全部亚科</option>'+sfs.map(v=>`<option value="${E(v)}">${E(v)} · ${E(data.find(x=>x.subfamily===v)?.subfamilyZh||'')}</option>`).join('');const sts=[...new Set(data.map(x=>x.recovery||x.status).filter(Boolean))].sort();$('#status').innerHTML='<option value="">全部恢复状态</option>'+sts.map(v=>`<option value="${E(v)}">${E(v)}</option>`).join('')}
function filtered(){const q=$('#q').value.trim().toLowerCase(),sf=$('#sf').value,cn=$('#cn').value,st=$('#status').value;return active().filter(x=>{const d=confirmedMap.get(x.sci)||x,hay=[x.zh,x.aliases,x.sci,x.genus,x.subfamily,x.spid,x.recovery,x.status,d.summary,d.distribution,d.habitat].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!sf||x.subfamily===sf)&&(!cn||cnState(x)===cn)&&(!st||(x.recovery||x.status)===st)}).sort((a,b)=>(!!b.zh-!!a.zh)||label(a).localeCompare(label(b),'zh-CN'))}
function list(){const a=filtered();$('#count').textContent=`显示 ${a.length} / ${active().length} 条 · ${mode==='confirmed'?'确认有图':'全部候选'}`;$('#list').innerHTML=a.map(x=>{const d=confirmedMap.get(x.sci),isOn=x.sci===selected;return`<div class="item ${isOn?'on':''}" data-sci="${E(x.sci)}"><div class="ico">${icon(x)}</div><div><div class="nm">${E(label(x))}</div><div class="sci">${E(x.sci)}</div><div class="badges"><span class="badge ${d?'deep':''}">${d?'确认有图':'候选'}</span>${/^是/.test(x.china||'')?'<span class="badge cn">中国</span>':''}${x.spid?`<span class="badge idb">ID ${E(x.spid)}</span>`:''}<span class="badge">${E(x.genus||'')}</span></div></div></div>`}).join('');document.querySelectorAll('.item').forEach(el=>el.onclick=()=>{selected=el.dataset.sci;list();center();$('.center')?.scrollTo({top:0,behavior:'smooth'})})}
function sourceLink(n,u,cls=''){return u?`<a class="${cls}" target="_blank" rel="noopener" href="${E(u)}">${E(n)}</a>`:''}
function picture(x){const m=IM[x.id];if(m?.file)return`<div class="photo"><img src="${E(m.file)}" alt="${E(label(x))}"><span class="imgev">本地图片</span></div><div class="credit">${E([m.source,m.photographer,m.license].filter(Boolean).join(' · '))}</div>`;const d=confirmedMap.get(x.sci),msg=d?'已有可追溯图片证据，本地图片仍在补齐':'当前未确认本地图片';return`<div class="photo"><div class="ph"><strong>${E(msg)}</strong>${d?.imageEvidence?E(d.imageEvidence):'不使用近缘种照片冒充。'}</div><span class="imgev ${d?'':'pending'}">${d?'有图证据':'待补图'}</span></div>`}
function metaRow(k,v){return v?`<b>${E(k)}</b><span>${E(v)}</span>`:''}
function center(){let d=confirmedMap.get(selected),c=candidateMap.get(selected),x=d||c;if(!x){x=active()[0];if(!x)return;selected=x.sci;d=confirmedMap.get(selected);c=candidateMap.get(selected)}const aw='https://www.antwiki.org/wiki/'+x.sci.replaceAll(' ','_'),antweb='https://www.antweb.org/description.do?genus='+encodeURIComponent(x.genus||'')+'&species='+encodeURIComponent(x.sci.split(' ')[1]||'');const src=[sourceLink('AntWiki',aw),sourceLink('AntWeb',antweb),sourceLink('ants-china',d?.antsChina||c?.antsChina,'sourceok'),sourceLink('IISDW',d?.iisdw),sourceLink('AntDen',d?.antden)].join('');
$('#hero').innerHTML=`<div class="hg"><div><div class="k">${d?'CONFIRMED IMAGE SPECIES':'RECOVERY CANDIDATE'} · ${E(d?.recovery||c?.status||'')}</div><h1>${E(label(x))}</h1><div class="latin">${E(x.sci)}</div>${d?.aliases?`<div class="alias">别名：${E(d.aliases)}</div>`:''}<div class="tax">${E(x.subfamilyZh||x.subfamily||'')} · ${E(x.subfamily||'')} · ${E(x.genus||'')}${x.spid?` · ants-china ID ${E(x.spid)}`:''}</div><div class="acts">${src}</div></div><div>${picture(x)}</div></div>`;
let cards='';if(d){const core=[metaRow('工蚁体长',d.worker),metaRow('兵蚁体长',d.soldier),metaRow('蚁后体长',d.queen),metaRow('雄蚁体长',d.male),metaRow('中国记录',d.china),metaRow('资料完整度',d.completeness?d.completeness+'%':''),metaRow('饲养温度',d.temp),metaRow('饲养湿度',d.humidity)].join('');cards+=`<div class="card wide verified"><h3>物种概览 <span class="ev">${E(d.recovery||'已恢复')}</span></h3><p>${E(d.summary||'该物种已进入确认有图主表；当前仅展示已核实或可追溯资料。')}</p></div>`;cards+=`<div class="card"><h3>核心参数</h3><div class="meta">${core||'<span class="muted">核心参数待补</span>'}</div></div>`;cards+=`<div class="card"><h3>分布与生境</h3><div class="meta">${metaRow('全球分布',d.distribution)}${metaRow('生境',d.habitat)}${metaRow('筑巢',d.nest)}${metaRow('食性',d.diet)}</div></div>`;if(d.identification)cards+=`<div class="card wide"><h3>形态与鉴别</h3><p>${E(d.identification)}</p></div>`;if(d.behavior||d.colony||d.flight)cards+=`<div class="card wide"><h3>行为、群落与婚飞</h3><p>${E([d.behavior,d.colony,d.flight&&('婚飞：'+d.flight)].filter(Boolean).join('；'))}</p></div>`;cards+=`<div class="card"><h3>证据等级</h3><div class="meta">${metaRow('图片',d.imageGrade)}${metaRow('分类',d.taxonomyEvidence)}${metaRow('生物',d.biologyEvidence)}${metaRow('饲养',d.husbandryEvidence)}</div></div>`;cards+=`<div class="card"><h3>图片证据</h3><p>${E(d.imageEvidence||'已确认有图，详细图片来源继续补齐。')}</p></div>`;if(d.conflict)cards+=`<div class="card wide"><h3>冲突 / 复核</h3><div class="warn">${E(d.conflict)}</div></div>`;if(d.missing)cards+=`<div class="card wide"><h3>仍待补充</h3><div class="missing">${E(d.missing)}</div></div>`}else{cards+=`<div class="card wide"><h3>候选恢复状态</h3><p>${E(c?.status||'当前未进入确认有图主表。')}</p></div>`;if(c?.imageEvidence)cards+=`<div class="card"><h3>图片证据</h3><p>${E(c.imageEvidence)}</p></div>`;if(c?.chineseDbTrace)cards+=`<div class="card"><h3>Chinese Ant Database 痕迹</h3><p>${E(c.chineseDbTrace)}</p></div>`;if(c?.sharedConflict||c?.conflict)cards+=`<div class="card wide"><h3>冲突 / 复核</h3><div class="warn">${E([c.sharedConflict,c.conflict].filter(Boolean).join('；'))}</div></div>`;if(c?.missing)cards+=`<div class="card wide"><h3>当前缺失</h3><div class="missing">${E(c.missing)}</div></div>`}cards+=`<div class="card wide"><h3>来源</h3><div class="links">${src}</div></div>`;$('#content').innerHTML=`<div class="grid">${cards}</div>`}
function renderMy(){const byId=new Map(CAND.map(x=>[x.id,x]));$('#mc').textContent=`${MY.length} 条`;$('#my').innerHTML=MY.map(m=>{const x=m.m?byId.get(m.m):null;return`<div class="mi" data-sci="${E(x?.sci||'')}"><div class="mr"><b>${E(m.l)}</b><span class="days">${E(m.d)}d</span></div><div class="st">${E(m.st)}${x?' · '+E(x.sci):''}</div></div>`}).join('');document.querySelectorAll('.mi').forEach(el=>{if(el.dataset.sci)el.onclick=()=>{selected=el.dataset.sci;if(!active().some(x=>x.sci===selected)){mode='all';syncMode()}list();center()}})}
function syncMode(){document.querySelectorAll('.modebtn').forEach(b=>b.classList.toggle('on',b.dataset.mode===mode));fillFilters();if(!active().some(x=>x.sci===selected))selected=active()[0]?.sci||'';list();center()}
async function boot(){try{const db=await loadDb();confirmedMap=new Map(CONF.map(x=>[x.sci,x]));candidateMap=new Map(CAND.map(x=>[x.sci,x]));selected=CONF[0]?.sci||CAND[0]?.sci||'';$('#confirmedStat').textContent=CONF.length;$('#candidateStat').textContent=CAND.length;$('#dataVersion').textContent=db.v||'2026-08-15';document.querySelectorAll('.modebtn').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;syncMode()});['#q','#sf','#cn','#status'].forEach(s=>$(s).addEventListener(s==='#q'?'input':'change',list));fillFilters();list();center();renderMy()}catch(err){$('#hero').innerHTML=`<div class="loading">数据库加载失败：${E(err.message||err)}</div>`;$('#content').innerHTML=''}}boot();
})();