(()=>{
'use strict';
const S=window.ANTDEX_SPECIES||[];
const IM=window.ANTDEX_IMAGES||{};
const $=s=>document.querySelector(s);
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const val=v=>(v===null||v===undefined||v===''?'待核':v);
let shown=60, sortMode='image';
const hasEvidence=x=>!!(x.imageEvidence||x.imageGrade||x.antsChina&&/有图/.test(x.recovery||''));
const img=x=>IM[x.id]||null;
const label=x=>x.zh||x.sci;
const cnState=x=>{const v=x.china||'';if(/^是/.test(v))return'yes';if(/否|非中国|未见/.test(v))return'no';return'unknown'};
function fillFilters(){const a=[...new Set(S.map(x=>x.subfamily).filter(Boolean))].sort();$('#sf').innerHTML='<option value="">全部亚科</option>'+a.map(v=>`<option value="${esc(v)}">${esc(v)} · ${esc(S.find(x=>x.subfamily===v)?.subfamilyZh||'')}</option>`).join('')}
function filtered(){const q=$('#q').value.trim().toLowerCase(),sf=$('#sf').value,im=$('#imgFilter').value,cn=$('#cnFilter').value;let a=S.filter(x=>{const hay=[x.zh,x.aliases,x.sci,x.accepted,x.genus,x.subfamily,x.summary].filter(Boolean).join(' ').toLowerCase();const okImg=!im||(im==='local'&&img(x))||(im==='evidence'&&hasEvidence(x))||(im==='missing'&&!img(x));return(!q||hay.includes(q))&&(!sf||x.subfamily===sf)&&okImg&&(!cn||cnState(x)===cn)});a.sort((x,y)=>{if(sortMode==='name')return label(x).localeCompare(label(y),'zh-CN');if(sortMode==='complete')return (+y.completeness||0)-(+x.completeness||0);const ix=img(x)?2:hasEvidence(x)?1:0,iy=img(y)?2:hasEvidence(y)?1:0;return iy-ix||(+y.completeness||0)-(+x.completeness||0)||label(x).localeCompare(label(y),'zh-CN')});return a}
function badge(x){if(img(x))return'<span class="img-badge">本地图片</span>';if(hasEvidence(x))return'<span class="img-badge evidence">已有图源 · 待缓存</span>';return'<span class="img-badge missing">待补图</span>'}
function picture(x){const m=img(x);if(m?.file)return`<img loading="lazy" src="${esc(m.file)}" alt="${esc(label(x))}" onerror="this.closest('.photo').classList.add('broken');this.remove()">`;return`<div class="ph"><div><div class="ph-mark">A</div><small>${hasEvidence(x)?'图片源已登记，等待本地缓存':'暂无可确认本地图像'}</small></div></div>`}
function card(x){return`<article class="card" data-id="${esc(x.id)}"><div class="photo">${picture(x)}${badge(x)}</div><div class="card-copy"><div class="zh">${esc(label(x))}</div><div class="sci">${esc(x.sci)}</div><div class="meta"><span class="tag sf">${esc(x.subfamilyZh||x.subfamily)}</span>${/^是/.test(x.china||'')?'<span class="tag cn">中国记录</span>':''}${x.spid?`<span class="tag">ID ${esc(x.spid)}</span>`:''}</div></div></article>`}
function render(reset=true){if(reset)shown=60;const a=filtered(),v=a.slice(0,shown);$('#count').textContent=`显示 ${Math.min(shown,a.length)} / ${a.length} 条 · 总库 ${S.length}`;$('#grid').innerHTML=v.map(card).join('');$('#empty').hidden=!!a.length;$('#more').hidden=shown>=a.length;document.querySelectorAll('.card').forEach(e=>e.onclick=()=>openDetail(S.find(x=>x.id===e.dataset.id)));$('#speciesStat').textContent=`${S.length} 物种`;$('#imageStat').textContent=`本地图片 ${Object.keys(IM).length} · 外部有图证据 ${S.filter(hasEvidence).length}`}
function fact(k,v){if(v===null||v===undefined||v==='')return'';return`<div class="fact"><b>${esc(k)}</b><span>${esc(v)}</span></div>`}
function links(x,m){const a=[];if(x.antsChina)a.push(['ants-china 原站',x.antsChina]);if(x.antwiki)a.push(['AntWiki',x.antwiki]);if(x.antweb)a.push(['AntWeb',x.antweb]);if(m?.source_page)a.push(['图片原页',m.source_page]);a.push(['Google 图片检索','https://www.google.com/search?tbm=isch&q='+encodeURIComponent('"'+x.sci+'" ant')]);return a.map(([n,u])=>`<a target="_blank" rel="noopener" href="${esc(u)}">${esc(n)}</a>`).join('')}
function openDetail(x){if(!x)return;const m=img(x);const hero=m?.file?`<img src="${esc(m.file)}" alt="${esc(label(x))}">`:`<div class="ph"><div><div class="ph-mark">A</div><small>${hasEvidence(x)?'图片源已登记，等待缓存任务补齐':'当前没有可确认的本地照片'}</small></div></div>`;const credit=m?`<div class="credit">图片：${esc(m.source||'公开图库')}${m.photographer?' · '+esc(m.photographer):''}${m.license?' · '+esc(m.license):''}${m.specimen_code?' · '+esc(m.specimen_code):''}${m.source_page?` · <a target="_blank" rel="noopener" href="${esc(m.source_page)}">查看来源</a>`:''}</div>`:'';const facts=[fact('工蚁体长',x.worker),fact('兵蚁体长',x.soldier),fact('蚁后体长',x.queen),fact('雄蚁体长',x.male),fact('中国记录',x.china),fact('全球分布',x.distribution),fact('生境',x.habitat),fact('筑巢',x.nest),fact('食性',x.diet),fact('婚飞',x.flight),fact('饲养温度',x.temp),fact('饲养湿度',x.humidity),fact('饲养难度',x.difficulty),fact('安全性',x.safety)].filter(Boolean).join('');$('#detail').innerHTML=`<div class="hero"><div class="hero-img">${hero}</div>${credit}<div class="hero-copy"><h2>${esc(label(x))}</h2><div class="latin">${esc(x.sci)}</div><div class="hero-tags"><span>${esc(x.subfamilyZh||x.subfamily)}</span><span>${esc(x.genus)}</span>${x.imageGrade?`<span>图片 ${esc(x.imageGrade)}</span>`:''}${x.spid?`<span>ants-china ID ${esc(x.spid)}</span>`:''}</div></div></div><div class="detail-body">${x.summary?`<section class="section"><h3>物种概览</h3><div class="prose">${esc(x.summary)}</div></section>`:''}<section class="section"><h3>核心资料</h3><div class="facts">${facts||'<div class="missingbox">核心参数仍待物种级资料补充。</div>'}</div></section>${x.identification?`<section class="section"><h3>形态与鉴别</h3><div class="prose">${esc(x.identification)}</div></section>`:''}${x.behavior||x.colony?`<section class="section"><h3>行为与群落</h3><div class="prose">${esc([x.behavior,x.colony].filter(Boolean).join('；'))}</div></section>`:''}${x.conflict?`<section class="section"><h3>分类/数据复核</h3><div class="warnbox">${esc(x.conflict)}</div></section>`:''}${x.missing?`<section class="section"><h3>仍待补充</h3><div class="missingbox">${esc(x.missing)}</div></section>`:''}<section class="section"><h3>图片与证据</h3><div class="image-source">${m?`<span class="evidence-pill">本地缓存</span>${esc(m.source||'')} ${esc(m.license||'')}`:`<span class="evidence-pill">${hasEvidence(x)?'已有外部图源':'待找图'}</span>${esc(x.imageEvidence||'当前暂无公开图片证据')}`}</div></section><section class="section"><h3>来源</h3><div class="links">${links(x,m)}</div></section></div>`;$('#backdrop').hidden=false;$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeDetail(){ $('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');$('#backdrop').hidden=true;document.body.style.overflow=''}
fillFilters();render();['#q','#sf','#imgFilter','#cnFilter'].forEach(s=>$(s).addEventListener(s==='#q'?'input':'change',()=>render(true)));document.querySelectorAll('.sortbtn').forEach(b=>b.onclick=()=>{sortMode=b.dataset.sort;document.querySelectorAll('.sortbtn').forEach(x=>x.classList.toggle('on',x===b));render(true)});$('#more').onclick=()=>{shown+=60;render(false)};$('#close').onclick=closeDetail;$('#backdrop').onclick=closeDetail;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
})();
