(()=>{'use strict';
let DATA=[],selected='',view='overview';
const MY=window.MY||[],IM=window.ANTDEX_IMAGES||{},RX=window.ANTDEX_RICH||{};
const $=s=>document.querySelector(s);
const E=v=>(v??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const expandC=o=>({id:o.i,zh:o.z,aliases:o.a,sci:o.s,accepted:o.ac,subfamily:o.f,subfamilyZh:o.fz,genus:o.g,distribution:o.d,habitat:o.h,ecoTags:o.et,nest:o.n,diet:o.di,summary:o.sm,colony:o.co,worker:o.w,soldier:o.so,queen:o.q,male:o.m,identification:o.idn,behavior:o.b,flight:o.fl,temp:o.t,humidity:o.hu,difficulty:o.df,safety:o.sa});
const expandA=o=>({id:o.i,zh:o.z,sci:o.s,accepted:o.ac,subfamily:o.f,subfamilyZh:o.fz,genus:o.g,aliases:o.la,distribution:o.ld,habitat:o.lh,ecoTags:o.let,nest:o.ln,diet:o.ldi,summary:o.lsm,worker:o.lw,workerDetail:o.lwd,queen:o.lq,temp:o.lt,humidity:o.lhu,husbandryWarning:o.lhw,nameNote:o.lnn});
async function ungzipB64(b64){const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));return await new Response(new Blob([bin]).stream().pipeThrough(new DecompressionStream('gzip'))).text()}
const empty=v=>v==null||v===''||(Array.isArray(v)&&!v.length);
function usable(v){if(empty(v))return'';const s=Array.isArray(v)?v.join('、'):String(v).trim();if(!s)return'';if(/^(待核|未核实|待物种级核实|待补|暂无|未知)$/i.test(s))return'';if(/图鉴收录条目|图鉴收录层|等待逐项核入|只保留可靠分类骨架|来源入口|当前仅展示已核实|未核实不填|不使用属级习性直接替代|公开数据库补充|原站.*恢复|历史资料|恢复状态|完整详情会按需读取公开百科简介|仅在原始描述.*(?:TL|body length)|可靠物种资料明确给出.*(?:TL|body length)|后导入/i.test(s))return'';return s}
const pick=(...xs)=>{for(const x of xs){const v=usable(x);if(v)return v}return''};
function mergeRecord(a,c,l){return{id:pick(c?.id,a?.id,l?.i)||a?.id||c?.id||'',zh:pick(c?.zh,a?.zh,l?.z,l?.zh),aliases:pick(c?.aliases,a?.aliases,l?.a),sci:pick(c?.sci,a?.sci,l?.s)||a?.sci||c?.sci,accepted:pick(c?.accepted,a?.accepted),subfamily:pick(c?.subfamily,a?.subfamily),subfamilyZh:pick(c?.subfamilyZh,a?.subfamilyZh),genus:pick(c?.genus,a?.genus),summary:pick(c?.summary,a?.summary,l?.sm),distribution:pick(c?.distribution,a?.distribution,l?.d),habitat:pick(c?.habitat,a?.habitat,l?.h),ecoTags:pick(c?.ecoTags,a?.ecoTags,l?.et),nest:pick(c?.nest,a?.nest,l?.n),diet:pick(c?.diet,a?.diet,l?.di),colony:pick(c?.colony,l?.co),worker:pick(c?.worker,a?.worker,l?.w),workerDetail:pick(a?.workerDetail,l?.wd),soldier:pick(c?.soldier,l?.so),queen:pick(c?.queen,a?.queen,l?.q),male:pick(c?.male,l?.m),identification:pick(c?.identification,l?.idn),behavior:pick(c?.behavior,l?.b),flight:pick(c?.flight,l?.fl),temp:pick(c?.temp,a?.temp,l?.t),humidity:pick(c?.humidity,a?.humidity,l?.hu),difficulty:pick(c?.difficulty,l?.df),safety:pick(c?.safety,l?.sa),husbandryWarning:pick(a?.husbandryWarning,l?.hw),nameNote:pick(a?.nameNote,l?.nn)}}
const RICH_FIELDS=['summary','distribution','habitat','ecoTags','nest','diet','colony','worker','workerDetail','soldier','queen','male','identification','behavior','ecology','flight','temp','humidity','difficulty','safety','husbandryWarning','nomenclature','nameNote'];
function applyRich(r){const z=RX[r.sci]||{};if(!Object.keys(z).length)return r;const verified=/已核|核验批次|verified/i.test(z.status||'');for(const k of RICH_FIELDS){const u=usable(z[k]);if(u&&(verified||!usable(r[k])))r[k]=u}if(Array.isArray(z.sources)&&z.sources.length)r.sources=z.sources;if(Array.isArray(z.regions)&&z.regions.length)r.regions=z.regions;r.richStatus=z.status||'';return r}
async function loadDb(){const b64=window.ANTDEX_DB_GZ||'';if(!b64)throw new Error('数据库文件未加载');if(!('DecompressionStream'in window))throw new Error('当前浏览器不支持数据库解压');const db=JSON.parse(await ungzipB64(b64)),conf=(db.c||[]).map(expandC),cand=(db.a||[]).map(expandA),cm=new Map(conf.map(x=>[x.sci,x]));let legacy={};if(window.ANTDEX_LEGACY_GZ){try{legacy=JSON.parse(await ungzipB64(window.ANTDEX_LEGACY_GZ))}catch(e){legacy={}}}const out=[],seen=new Set();for(const a of cand){const r=applyRich(mergeRecord(a,cm.get(a.sci),legacy[a.sci]));if(r.sci){out.push(r);seen.add(r.sci)}}for(const c of conf){if(!seen.has(c.sci)){const r=applyRich(mergeRecord(null,c,legacy[c.sci]));out.push(r);seen.add(c.sci)}}DATA=out.sort((a,b)=>(+!!b.zh-+!!a.zh)||(a.zh||a.sci).localeCompare(b.zh||b.sci,'zh-CN'));return db}
function icon(x){const f=x.subfamily||'',v='viewBox="0 0 72 72"';if(f==='Myrmicinae')return`<svg ${v}><path d="M7 36h15M50 36h15"/><ellipse cx="30" cy="36" rx="8" ry="12"/><ellipse cx="44" cy="36" rx="7" ry="10"/></svg>`;if(f==='Myrmeciinae')return`<svg ${v}><circle class="eye" cx="26" cy="25" r="17"/><path class="a" d="M23 45 7 67M31 45 45 67"/></svg>`;if(['Ponerinae','Amblyoponinae','Paraponerinae','Ectatomminae'].includes(f))return`<svg ${v}><ellipse cx="27" cy="38" rx="12" ry="17"/><path class="a" d="M39 39Q57 32 68 16"/></svg>`;return`<svg ${v}><ellipse cx="28" cy="38" rx="12" ry="17"/><circle class="a" cx="57" cy="38" r="9"/></svg>`}
function fillFilters(){const sfs=[...new Set(DATA.map(x=>x.subfamily).filter(Boolean))].sort();$('#sf').innerHTML='<option value="">全部亚科</option>'+sfs.map(v=>`<option value="${E(v)}">${E(v)} · ${E(DATA.find(x=>x.subfamily===v)?.subfamilyZh||'')}</option>`).join('')}
function filtered(){const q=$('#q').value.trim().toLowerCase(),sf=$('#sf').value;return DATA.filter(x=>{const hay=[x.zh,x.aliases,x.sci,x.genus,x.subfamily,x.summary,x.distribution,x.habitat,x.identification,x.ecology].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!sf||x.subfamily===sf)})}
function selectSpecies(sci){selected=sci;view='overview';list();center();$('.center')?.scrollTo({top:0,behavior:'smooth'})}
function list(){const a=filtered();$('#count').textContent=`${a.length} 种`;$('#list').innerHTML=a.map(x=>`<div class="item ${x.sci===selected?'on':''}" data-sci="${E(x.sci)}"><div class="ico">${icon(x)}</div><div><div class="nm">${E(x.zh||x.sci)}</div><div class="sci">${E(x.sci)}</div></div></div>`).join('');document.querySelectorAll('.item').forEach(el=>el.onclick=()=>selectSpecies(el.dataset.sci))}
function picture(x){const m=IM[x.id];if(m?.file)return`<div class="photo"><img src="${E(m.file)}" alt="${E(x.zh||x.sci)}"></div><div class="credit">${E([m.photographer,m.license].filter(Boolean).join(' · '))}</div>`;return`<div class="photo"><div class="ph"><strong>${E(x.zh||x.sci)}</strong><br>图片加载中</div></div>`}
const row=(k,v)=>usable(v)?`<b>${E(k)}</b><span>${E(usable(v))}</span>`:'';
function card(title,body,cls=''){return body?`<div class="card ${cls}"><h3>${E(title)}</h3>${body}</div>`:''}
function para(v){const s=usable(v);return s?`<p>${E(s)}</p>`:''}
function section(title,v){const s=usable(v);return s?`<h4>${E(title)}</h4><p>${E(s)}</p>`:''}
function cleanSentence(s){return String(s||'').trim().replace(/[。；;，,\s]+$/,'')}
function introText(x){const direct=usable(x.summary);if(direct)return direct;const name=x.zh||x.sci,parts=[];let lead=`${name}${x.zh&&x.sci?`（${x.sci}）`:''}`,tax=[];if(usable(x.genus))tax.push(`${x.genus}属`);if(usable(x.subfamilyZh))tax.push(x.subfamilyZh);else if(usable(x.subfamily))tax.push(x.subfamily);if(tax.length)lead+=`隶属于${tax.join('、')}`;lead+='。';parts.push(lead);const dist=usable(x.distribution),hab=usable(x.habitat),worker=usable(x.worker),queen=usable(x.queen);if(dist)parts.push(`分布方面，${cleanSentence(dist)}。`);if(hab)parts.push(`常见生境包括${cleanSentence(hab)}。`);if(worker||queen){const sz=[];if(worker)sz.push(`工蚁${cleanSentence(worker)}`);if(queen)sz.push(`蚁后${cleanSentence(queen)}`);parts.push(`体型方面，${sz.join('，')}。`)}return parts.join('')}
function coreRows(x){return[row('工蚁',x.worker),row('兵蚁',x.soldier),row('蚁后',x.queen),row('雄蚁',x.male),row('温度',x.temp),row('湿度',x.humidity)].join('')}
function husbandryRows(x){return[row('温度',x.temp),row('湿度',x.humidity),row('巢穴/保湿',x.nest),row('食物',x.diet),row('饲养难度',x.difficulty),row('注意事项',x.husbandryWarning||x.safety)].join('')}
function sourceLinks(x){if(!Array.isArray(x.sources)||!x.sources.length)return'';return`<div class="links">${x.sources.map(a=>`<a target="_blank" rel="noopener" href="${E(a[1])}">${E(a[0])}${a[2]?` · ${E(a[2])}`:''}</a>`).join('')}</div>`}
function taxonomy(x){return[row('学名',x.sci),row('接受名',x.accepted),row('亚科',x.subfamilyZh?`${x.subfamily} · ${x.subfamilyZh}`:x.subfamily),row('属',x.genus),row('中文名',x.zh),row('别名',x.aliases)].join('')}
function overview(x){$('#hero').innerHTML=`<div class="hg"><div><div class="k">${E(x.subfamilyZh||x.subfamily||'蚂蚁图鉴')}</div><h1>${E(x.zh||x.sci)}</h1><div class="latin">${E(x.sci)}</div>${usable(x.aliases)?`<div class="alias">别名：${E(usable(x.aliases))}</div>`:''}<div class="tax">${E([x.subfamilyZh||x.subfamily,x.genus].filter(Boolean).join(' · '))}</div><div class="acts"><button class="dark" id="full">查看完整详情 →</button></div></div><div>${picture(x)}</div></div>`;const core=coreRows(x),eco=section('分布',x.distribution)+section('生境',x.habitat),nestDiet=section('巢穴',x.nest)+section('食性',x.diet),intro=introText(x);$('#content').innerHTML=`<div class="grid">${card('物种介绍',para(intro),'wide intro')}${core?card('核心参数',`<div class="meta">${core}</div>`):''}${card('生态与分布',eco)}${card('巢穴与食性',nestDiet)}</div>`;$('#full').onclick=()=>{view='full';center();$('.center')?.scrollTo({top:0,behavior:'smooth'})}}
function fullDetail(x){$('#hero').innerHTML=`<div class="fullbar"><button class="ghost" id="back">← 返回物种概览</button><div><div class="k">完整详情</div><b>${E(x.zh||x.sci)}</b><i>${E(x.sci)}</i></div></div>`;const intro=para(introText(x)),core=coreRows(x),tax=taxonomy(x),ecology=section('分布',x.distribution)+section('生境',x.habitat)+section('生态特征',x.ecoTags)+section('生态与群落',x.ecology),morphology=section('形态与鉴别',x.identification)+section('体型补充',x.workerDetail),life=section('巢穴',x.nest)+section('食性',x.diet)+section('行为',x.behavior),colony=section('群落与繁殖',x.colony)+section('婚飞',x.flight),husbandry=husbandryRows(x),taxonomyMore=section('分类与命名',x.nomenclature)+section('补充说明',x.nameNote),sources=sourceLinks(x);$('#content').innerHTML=`<div class="grid detailgrid">${card('完整物种介绍',intro,'wide intro')}${tax?card('分类与名称',`<div class="meta">${tax}</div>`):''}${core?card('核心参数',`<div class="meta">${core}</div>`):''}${card('生态与分布',ecology,'wide details')}${card('形态与鉴别',morphology,'wide details')}${card('巢穴、食性与行为',life,'wide details')}${card('群落、繁殖与婚飞',colony,'wide details')}${husbandry?card('饲养指南',`<div class="meta">${husbandry}</div>`,'wide husbandry'):''}${card('分类、命名与补充',taxonomyMore,'wide details')}${card('资料来源',sources,'wide')}</div>`;$('#back').onclick=()=>{view='overview';center();$('.center')?.scrollTo({top:0,behavior:'smooth'})}}
function center(){let x=DATA.find(v=>v.sci===selected);if(!x){x=DATA[0];if(!x)return;selected=x.sci}if(view==='full')fullDetail(x);else overview(x)}
function renderMy(){const byId=new Map(DATA.map(x=>[x.id,x]));$('#mc').textContent=`${MY.length} 条`;$('#my').innerHTML=MY.map(m=>{const x=m.m?byId.get(m.m):null;return`<div class="mi" data-sci="${E(x?.sci||'')}"><div class="mr"><b>${E(m.l)}</b><span class="days">${E(m.d)}d</span></div><div class="st">${E(m.st)}${x?' · '+E(x.zh||x.sci):''}</div></div>`}).join('');document.querySelectorAll('.mi').forEach(el=>{if(el.dataset.sci)el.onclick=()=>selectSpecies(el.dataset.sci)})}
async function boot(){try{await loadDb();$('#speciesStat').textContent=DATA.length;selected=DATA[0]?.sci||'';fillFilters();$('#q').addEventListener('input',list);$('#sf').addEventListener('change',list);list();center();renderMy();window.ANTDEX_GET_RECORD=sci=>DATA.find(x=>x.sci===sci)||null;window.ANTDEX_ATLAS_DIAGNOSTICS={records:DATA.length,rich:Object.keys(RX).length,importLog:[...(window.ANTDEX_IMPORT_LOG||[])],conflicts:[...(window.ANTDEX_IMPORT_CONFLICTS||[])]}}catch(err){$('#hero').innerHTML=`<div class="loading">数据库加载失败：${E(err.message||err)}</div>`}}boot();
})();