(()=>{'use strict';
const CURRENT={
'Messor structor':'工匠收获蚁','Messor angularis':'角收获蚁','Messor cephalotes':'肯尼亚收获蚁','Messor arenarius':'沙地收获蚁','Messor hebraeus':'希伯来收获蚁','Messor barbarus':'原生收获蚁','Messor aciculatus':'针毛收获蚁','Messor laboriosus':'勤劳收获蚁','Messor minusculus':'无微颚齿收获蚁','Messor nondentatus':'强壮收获蚁','Myrmecocystus mimicus':'拟态蜜蚁','Myrmecocystus placodops':'平眼蜜罐蚁','Myrmecocystus mexicanus':'墨西哥蜜罐蚁','Myrmecocystus semirufus':'半红蜜罐蚁','Cataglyphis bombycina':'银丝箭蚁','Atta sexdens':'阿塔切叶蚁','Atta cephalotes':'阿塔切叶蚁','Atta mexicana':'阿塔切叶蚁','Acromyrmex octospinosus':'八刺顶切叶蚁','Odontomachus monticola':'山大齿猛蚁','Camponotus angusticollis':'窄颈弓背蚁','Camponotus japonicus':'日本弓背蚁','Camponotus turkestanus':'黑斑/黑金土耳其弓背蚁','Camponotus nicobarensis':'尼科巴弓背蚁','Camponotus fedtschenkoi':'费氏弓背蚁/红金弓背蚁','Carebara diversa':'全异巨首蚁','Tetramorium trimeni':'津岛铺道蚁','Camponotus singularis':'红头弓背蚁','Oecophylla smaragdina':'黄猄蚁','Harpegnathos venator':'猎镰猛蚁','Pheidole sinica':'中华四节大头蚁','Proformica mongolica':'中华蜜罐蚁/蒙古原蚁','Monomorium chinense':'中华小家蚁','Camponotus obscuripes':'暗足弓背蚁','Camponotus pseudoirritans':'拟光腹弓背蚁','Myopopone castanea':'红矛猛蚁','Myrmicaria brunnea':'褐色脊红蚁','Tetramorium bicarinatum':'双隆骨铺道蚁','Camponotus mutilarius':'香斑弓背蚁','Camponotus pseudolendus':'拟哀弓背蚁','Camponotus nipponicus':'黑平截弓背蚁','Camponotus mitis':'平和弓背蚁','Acanthomyrmex glabfemoralis':'光腿刺切叶蚁','Polyrhachis lamellidens':'叶型多刺蚁','Carebara lignata':'木盲切叶蚁','Pheidole yeensis':'伊大头蚁','Anoplolepis gracilipes':'长足捷蚁','Anoplolepis custodiens':'黑腹捷蚁','Camponotus lasiselene':'毛钳弓背蚁','Gnamptogenys bicolor':'双色曲颊猛蚁','Crematogaster rogenhoferi':'黑褐举腹蚁','Diacamma rugosum':'聚纹双刺猛蚁','Odontomachus silvestrii':'西氏大齿猛蚁','Ectomomyrmex astutus':'敏捷扁头猛蚁','Camponotus aethiops':'艾提弓背蚁','Gnamptogenys binghamii':'宾氏曲颊猛蚁','Camponotus turkestanicus':'突厥弓背蚁','Camponotus albosparsus':'黄斑弓背蚁','Camponotus dolendus':'巴瑞弓背蚁','Polyrhachis dives':'拟黑多刺蚁','Lasius alienus':'玉米毛蚁','Meranoplus bicolor':'二色盾胸切叶蚁','Pristomyrmex brevispinosus':'短刺棱胸切叶蚁','Pheidole noda':'宽结大头蚁','Aphaenogaster japonica':'中日盘腹蚁'
};
const URL='https://www.antscn.shop/antscn';
let last='';
function sci(){return document.querySelector('#hero .latin')?.textContent?.trim()||''}
function removeFalseAbsence(){
 document.querySelectorAll('.sourcecard.supplemental').forEach(el=>{const t=el.textContent||'';if(/ants-china.*(尚未恢复|没有可验证|未恢复)/i.test(t))el.remove()});
 document.querySelectorAll('#hero .acts .muted').forEach(el=>{if(/ants-china.*(尚未恢复|未恢复|没有)/i.test(el.textContent||''))el.remove()});
 document.querySelectorAll('.card').forEach(el=>{const t=el.textContent||'';if(/本条当前没有可验证的\s*ants-china\s*原站页面/i.test(t))el.remove()});
}
function removeWrongChinaNo(name){if(name!=='Messor structor')return;document.querySelectorAll('#content .meta b').forEach(b=>{if(b.textContent.trim()!=='中国记录')return;const v=b.nextElementSibling;if(v&&/否|未见/.test(v.textContent||'')){b.remove();v.remove()}})}
function addCurrentSource(name){const zh=CURRENT[name];if(!zh)return;const grid=document.querySelector('#content .grid');if(!grid||grid.querySelector('.antscn-current'))return;const card=document.createElement('div');card.className='card wide sourcecard exact antscn-current';card.innerHTML='<h3>AntsChina 当前目录 <span class="ev">已收录</span></h3><p><b>'+escapeHtml(name)+'</b> — '+escapeHtml(zh)+' 已明确列在 AntsChina 当前目录中。</p><div class="links"><a class="sourceok" target="_blank" rel="noopener" href="'+URL+'">查看 AntsChina 当前目录</a></div>';grid.prepend(card)}
function addListBadges(){document.querySelectorAll('#list .item').forEach(item=>{const s=item.querySelector('.sci')?.textContent?.trim();if(!s||!CURRENT[s]||item.querySelector('.antscn-now'))return;const box=item.querySelector('.badges');if(!box)return;const span=document.createElement('span');span.className='badge srcmain antscn-now';span.textContent='AntsChina当前';box.prepend(span)})}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function run(){const name=sci();removeFalseAbsence();removeWrongChinaNo(name);addCurrentSource(name);addListBadges();last=name}
const obs=new MutationObserver(()=>{clearTimeout(window.__antdexFixTimer);window.__antdexFixTimer=setTimeout(run,40)});obs.observe(document.body,{subtree:true,childList:true});setTimeout(run,400);
})();
