(()=>{
const RX=window.ANTDEX_RICH||{};
const RT=JSON.parse(localStorage.getItem('antdex:runtimeFacts:v2')||'{}');
function good(v){return !!v&&!['待核','待物种级核实','待核原始描述','暂无可靠总长数据','暂无可靠总长数据 / 待核原始描述'].includes(String(v).trim())}
function rr(x){return RX[x.s]||{}}
function pv3(x,k){const r=rr(x),u=RT[x.s]||{};if(good(x[k]))return x[k];if(k==='w'&&good(r.worker))return r.worker;if(k==='q'&&good(r.queen))return r.queen;if(good(u[k]))return u[k];return '待核'}
function gtrans(url){return 'https://translate.google.com/translate?sl=auto&tl=zh-CN&u='+encodeURIComponent(url)}
function rich3(x){const r=rr(x);if(!Object.keys(r).length)return'';const fs=[['分布',r.distribution],['形态与鉴别',r.identification],['生态/群落',r.ecology],['分类与命名',r.nomenclature]].filter(v=>v[1]);return`<div class="card wide verified"><h3>AntDex 已整理中文资料 <span class="ev">${E(r.status||'已核')}</span></h3>${r.summary?`<p class="detaillead">${E(r.summary)}</p>`:''}<div class="richfacts">${fs.map(v=>`<div><b>${E(v[0])}</b><p>${E(v[1])}</p></div>`).join('')}</div>${r.sources?.length?`<div class="links richlinks">${r.sources.map(a=>`<a target="_blank" href="${a[1]}">${E(a[0])} · ${E(a[2])}</a>`).join('')}</div>`:''}</div>`}
async function fetchText(api,title,ms=5000){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),ms);try{const q=new URLSearchParams({action:'query',format:'json',origin:'*',prop:'extracts',explaintext:'1',redirects:'1',titles:title});const r=await fetch(api+'?'+q,{signal:ctl.signal,cache:'force-cache'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json(),p=Object.values(d.query?.pages||{}).find(v=>v.extract&&v.missing===undefined);return p?.extract||''}catch(e){return''}finally{clearTimeout(tm)}}
function sentences(t){return (t||'').replace(/\r/g,'').split(/(?<=[。！？.!?])\s+|\n+/).map(s=>s.trim()).filter(s=>s.length>30&&s.length<500)}
function pick(t){const ss=sentences(t),cfg=[['分布',/distribution|range|native|found|localit|分布|原产|模式产地/i],['体型与品级',/worker|queen|male|length|工蚁|蚁后|雄蚁|体长/i],['巢穴与群落',/nest|colony|巢|群落/i],['形态与鉴别',/identification|colour|color|mandible|petiole|eye|鉴别|体色|上颚|腹柄|复眼/i],['生态与行为',/biology|habitat|forag|hunt|prey|desert|forest|生态|生境|觅食|荒漠|森林/i],['分类与命名',/described|nomenclature|status as species|type-material|描述|命名|分类/i]];return cfg.map(([n,re])=>[n,ss.find(s=>re.test(s))]).filter(v=>v[1]).slice(0,5)}
async function loadPublic3(x){const b=document.querySelector('#sourceDetail');if(!b)return;const r=rr(x);if(Object.keys(r).length){b.innerHTML=`<h3>补充公开来源</h3><div class="source-note">上方中文资料已预先整理入库，不需要等待浏览器现场翻译。下面仅补充检查其他公开来源；即使某个来源无法读取，也不会影响详情页。</div><div id="liveSources"><p class="muted">正在检查可读取的补充来源…</p></div>`}else{b.innerHTML=`<h3>公开来源资料</h3><div class="source-note">正在读取可公开访问的物种级资料。每个来源独立加载，最长等待约5秒，不会无限停留。</div><div id="liveSources"><p class="muted">正在读取…</p></div>`}
const out=[];const render=()=>{const box=document.querySelector('#liveSources');if(!box)return;if(!out.length){box.innerHTML='<p class="muted">暂未读取到新的站内摘要。</p>';return}box.innerHTML=out.map(o=>`<div class="srcblock"><div class="srctitle srcname">${E(o.name)} ${o.zh?'':'<span class="machine">英文原文</span>'}<a target="_blank" href="${o.url}">查看原文</a>${o.zh?'':`<a target="_blank" href="${gtrans(o.url)}">Google翻译打开</a>`}</div>${o.facts.map(f=>`<div class="factrow"><b>${E(f[0])}</b><div><p>${E(f[1].slice(0,260))}</p></div></div>`).join('')}</div>`).join('')};
const jobs=[
 ['中文 Wikipedia','https://zh.wikipedia.org/w/api.php',x.s,true,'https://zh.wikipedia.org/w/index.php?search='+encodeURIComponent(x.s)],
 ['AntWiki','https://www.antwiki.org/w/api.php',x.s.replaceAll(' ','_'),false,'https://www.antwiki.org/wiki/'+x.s.replaceAll(' ','_')],
 ['英文 Wikipedia','https://en.wikipedia.org/w/api.php',x.s,false,'https://en.wikipedia.org/wiki/'+x.s.replaceAll(' ','_')]
];
await Promise.allSettled(jobs.map(async j=>{const text=await fetchText(j[1],j[2],5000);if(!text)return;const fs=pick(text);if(fs.length){out.push({name:j[0],zh:j[3],url:j[4],facts:fs});render()}}));
render();
}
window.full=function(x){document.querySelector('#hero').innerHTML=`<div class="fullbar"><button class="ghost" id="back">← 返回物种概览</button><b>${E(lab(x))}</b><i>${E(x.s)}</i></div>`;document.querySelector('#content').innerHTML=`<div class="grid"><div class="card"><h3>分类信息</h3><div class="meta"><b>学名</b><span><i>${E(x.s)}</i></span><b>属</b><span>${E(x.g)}</span><b>亚科</b><span>${E(x.f+' · '+(x.fz||SF[x.f]||''))}</span><b>等级</b><span>${E(x.r)}</span></div></div><div class="card"><h3>核心参数</h3><div class="meta"><b>工蚁</b><span>${E(pv3(x,'w'))}</span><b>蚁后</b><span>${E(pv3(x,'q'))}</span><b>温度</b><span>${E(pv3(x,'t'))}</span><b>湿度</b><span>${E(pv3(x,'hu'))}</span></div><div class="source-note">核心参数和详细资料共用同一套已核字段；没有可靠物种级证据时仍显示“待核”。</div></div>${rich3(x)}<div class="card wide"><div class="photo" id="fp"><div class="ph">加载自然 / 生态照片…</div></div></div><div class="card wide" id="sourceDetail"><h3>公开来源资料</h3><p>准备中…</p></div><div class="card wide"><h3>AntWeb 标准标本照</h3><p style="margin-bottom:10px">用于 HEAD / PROFILE / DORSAL 形态观察。</p><div class="gallery" id="gal"><div class="empty">加载中…</div></div></div><div class="card wide"><h3>来源</h3>${links(x)}</div></div>`;document.querySelector('#back').onclick=()=>{mode=0;center()};natural(x,'fp');antweb(x);loadPublic3(x)};
})();