(()=>{
const RX=window.ANTDEX_RICH||{};
const RT=JSON.parse(localStorage.getItem('antdex:runtimeFacts:v2')||'{}');
const TT=JSON.parse(localStorage.getItem('antdex:translations:v2')||'{}');
const style=document.createElement('style');style.textContent=`
.sourceok{background:#e8f6f1;color:#23745c}.source-note{font-size:10px;line-height:1.55;color:#71808b;background:#f6f9fb;border-radius:7px;padding:8px;margin-top:10px}.verified{border-color:#b9dccd;background:linear-gradient(180deg,#fbfffd,#fff)}.verified .ev{font-size:9px;background:#dff2e9;color:#267353;border-radius:999px;padding:3px 6px;margin-left:5px}.richfacts{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.richfacts>div{background:#f7faf9;border-radius:8px;padding:10px}.richfacts b{font-size:11px;color:#3d6f5d}.richfacts p{margin-top:5px}.srcblock{margin-top:12px;border-top:1px dashed #d9e2e8;padding-top:10px}.srctitle{font-size:12px;font-weight:800;color:#2d6f9f;margin-bottom:8px}.factrow{display:grid;grid-template-columns:95px 1fr;gap:10px;margin:7px 0}.factrow>b{font-size:11px;color:#6c7780;padding-top:2px}.factrow p{margin:0 0 5px;font-size:12px;line-height:1.65}.muted{color:#7b8790}.machine{font-size:9px;color:#8a6e31;background:#fff7df;border-radius:5px;padding:2px 5px}.srcname{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.autofact{color:#267353;font-size:9px}.detaillead{font-size:13px;line-height:1.75;color:#4e5a64}.sourcefail{padding:10px;background:#fff8ef;border-radius:8px;font-size:11px;color:#80663f}.sourcefail a{color:#1769a9}.richlinks{margin-top:10px}@media(max-width:720px){.richfacts{grid-template-columns:1fr}.factrow{grid-template-columns:1fr}}
`;document.head.appendChild(style);
function rr(x){return RX[x.s]||{}}
function good(v){return !!v&&!['待核','待物种级核实','待核原始描述','暂无可靠总长数据','暂无可靠总长数据 / 待核原始描述'].includes(String(v).trim())}
function pv(x,k){let r=rr(x),u=RT[x.s]||{};if(good(x[k]))return x[k];if(k==='w'&&good(r.worker))return r.worker;if(k==='q'&&good(r.queen))return r.queen;if(good(u[k]))return u[k];return '待核'}
function googleLink(url){return 'https://translate.google.com/translate?sl=auto&tl=zh-CN&u='+encodeURIComponent(url)}
window.links=function(x){let aw='https://www.antwiki.org/wiki/'+x.s.replaceAll(' ','_'),wp='https://en.wikipedia.org/wiki/'+x.s.replaceAll(' ','_'),zw='https://zh.wikipedia.org/w/index.php?search='+encodeURIComponent(x.s);return`<div class="links"><a target="_blank" href="https://antcat.org/">AntCat</a><a target="_blank" href="https://www.catalogueoflife.org/">COL</a><a target="_blank" href="https://www.antweb.org/">AntWeb</a><a target="_blank" href="${aw}">AntWiki</a><a target="_blank" href="${googleLink(aw)}">Google翻译 AntWiki</a>${x.ac?`<a target="_blank" href="${x.ac}">ants-china</a>`:''}<a target="_blank" href="${zw}">中文Wikipedia</a><a target="_blank" href="${wp}">英文Wikipedia</a></div>`}
function richCards(x){let r=rr(x);if(!Object.keys(r).length)return'';let fields=[['分布',r.distribution],['形态与鉴别',r.identification],['生态/群落',r.ecology],['分类与命名',r.nomenclature]].filter(a=>a[1]);return`<div class="card wide verified"><h3>AntDex 已核物种资料 <span class="ev">${E(r.status||'已核')}</span></h3>${r.summary?`<p class="detaillead">${E(r.summary)}</p>`:''}<div class="richfacts">${fields.map(a=>`<div><b>${E(a[0])}</b><p>${E(a[1])}</p></div>`).join('')}</div>${r.sources?.length?`<div class="links richlinks">${r.sources.map(a=>`<a target="_blank" href="${a[1]}">${E(a[0])} · ${E(a[2])}</a>`).join('')}</div>`:''}</div>`}
function mm(a,b){let x=parseFloat(a),y=b?parseFloat(b):null;if(!Number.isFinite(x))return'';return Number.isFinite(y)?`${x}–${y} mm`:`${x} mm`}
function sizeFrom(text,who){let T=(text||'').replace(/\u00a0/g,' '),sub=who==='w'?'(?:工蚁|workers?|worker ants?)':'(?:蚁后|有翅蚁后|拟工蚁型蚁后|queens?|female(?:s)?)';let rs=[new RegExp(sub+'[^。.!?\\n]{0,180}?(?:体长|length|measure(?:s|d|ing)?)?[^0-9]{0,35}(\\d+(?:\\.\\d+)?)\\s*(?:mm|millimet(?:er|re)s?)?\\s*(?:[-–—~～]|to|至|到)\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|millimet(?:er|re)s?)','i'),new RegExp(sub+'[^。.!?\\n]{0,150}?(\\d+(?:\\.\\d+)?)\\s*(?:mm|millimet(?:er|re)s?)','i')];for(let re of rs){let m=T.match(re);if(m)return mm(m[1],m[2])}return''}
async function mw(api,title,search=false){try{let q;if(search){q=new URLSearchParams({action:'query',format:'json',origin:'*',generator:'search',gsrsearch:'"'+title+'"',gsrnamespace:'0',gsrlimit:'5',prop:'extracts',explaintext:'1'});}else{q=new URLSearchParams({action:'query',format:'json',origin:'*',prop:'extracts',explaintext:'1',redirects:'1',titles:title});}let r=await fetch(api+'?'+q,{cache:'force-cache'}),d=await r.json(),p=Object.values(d.query?.pages||{}).find(v=>v.extract&&v.missing===undefined);if(p?.extract)return p.extract}catch(e){}
 try{let q=new URLSearchParams({action:'parse',format:'json',origin:'*',page:title,prop:'text',redirects:'1'}),r=await fetch(api+'?'+q,{cache:'force-cache'}),d=await r.json(),h=d.parse?.text?.['*'];if(h){let doc=new DOMParser().parseFromString(h,'text/html');doc.querySelectorAll('table,style,script,sup,.mw-editsection,.toc,figure,.navbox').forEach(n=>n.remove());return doc.body.textContent.replace(/\s+/g,' ').trim()}}catch(e){}return''}
function isZh(t){let n=(t.match(/[\u3400-\u9fff]/g)||[]).length;return n>Math.max(8,t.length*.08)}
async function translate(t){if(!t||isZh(t))return t;let key=t.slice(0,240);if(TT[key])return TT[key];try{let parts=[],s=t;while(s){let c=Math.min(750,s.length),j=s.lastIndexOf('. ',c);if(j>350)c=j+1;parts.push(s.slice(0,c));s=s.slice(c)}let out=[];for(let p of parts.slice(0,3)){let u='https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=zh-CN&dt=t&q='+encodeURIComponent(p),r=await fetch(u),d=await r.json();out.push((d[0]||[]).map(a=>a[0]).join(''))}let z=out.join('');if(z){TT[key]=z;try{localStorage.setItem('antdex:translations:v2',JSON.stringify(TT))}catch(e){}return z}}catch(e){}return t}
function sents(t){return (t||'').replace(/\r/g,'').split(/(?<=[。！？.!?])\s+|\n+/).map(s=>s.trim()).filter(s=>s.length>22&&s.length<550)}
function facts(t){let ss=sents(t),cfg=[['分布',/distribution|region|found|native|range|localit|分布|原产|发现于|模式产地/i],['体型与品级',/worker|queen|ergatoid|male|length|measure|工蚁|蚁后|拟工蚁|雄蚁|体长/i],['巢穴与群落',/nest|mound|colony|workers|巢|土丘|群落|蚁巢/i],['形态与鉴别',/identification|body colou?r|mandible|eye|petiole|head|鉴别|体色|上颚|复眼|腹柄/i],['生态与行为',/biology|habitat|forag|hunt|prey|desert|forest|生态|生境|捕猎|觅食|荒漠|森林/i],['分类与命名',/described|nomenclature|status as species|type-material|authority|描述|命名|分类/i]];return cfg.map(([n,re])=>[n,ss.find(s=>re.test(s))]).filter(a=>a[1]).slice(0,5)}
async function sourceDetail2(x){let b=$('#sourceDetail');if(!b)return;b.innerHTML='<h3>公开来源资料整理</h3><p class="muted">正在读取 AntWiki / Wikipedia 的物种级正文；英文事实将尝试用 Google 翻译转成中文……</p>';let awUrl='https://www.antwiki.org/wiki/'+x.s.replaceAll(' ','_');let [zh,aw,en]=await Promise.all([mw('https://zh.wikipedia.org/w/api.php',x.s).then(v=>v||mw('https://zh.wikipedia.org/w/api.php',x.s,true)),mw('https://www.antwiki.org/w/api.php',x.s.replaceAll(' ','_')),mw('https://en.wikipedia.org/w/api.php',x.s)]);let src=[['中文 Wikipedia',zh,false,'https://zh.wikipedia.org/w/index.php?search='+encodeURIComponent(x.s)],['AntWiki',aw,true,awUrl],['英文 Wikipedia',en,true,'https://en.wikipedia.org/wiki/'+x.s.replaceAll(' ','_')]].filter(a=>a[1]);let all=src.map(a=>a[1]).join('\n'),r=rr(x),u=RT[x.s]||{};if(!good(x.w)&&!good(r.worker)){let z=sizeFrom(all,'w');if(z)u.w=z}if(!good(x.q)&&!good(r.queen)){let z=sizeFrom(all,'q');if(z)u.q=z}if(u.w||u.q){RT[x.s]=u;try{localStorage.setItem('antdex:runtimeFacts:v2',JSON.stringify(RT))}catch(e){}let a=$('#coreWorker'),q=$('#coreQueen');if(a)a.textContent=pv(x,'w');if(q)q.textContent=pv(x,'q')}
 if(!src.length){b.innerHTML=`<h3>公开来源资料整理</h3><div class="sourcefail">当前浏览器未能直接读取来源正文。你仍可打开 <a target="_blank" href="${awUrl}">AntWiki</a>，或直接用 <a target="_blank" href="${googleLink(awUrl)}">Google 翻译成中文</a>。站内不会因此拿属级资料补物种参数。</div>`;return}
 let h='<h3>公开来源资料整理</h3><div class="source-note">以下为物种级公开资料的短摘要。英文内容优先尝试 Google 机器翻译；机器翻译只改变语言，不改变证据等级。</div>';for(let [name,text,need,url] of src){let fs=facts(text);if(!fs.length)continue;h+=`<div class="srcblock"><div class="srctitle srcname">${E(name)}${need?'<span class="machine">自动中文翻译</span>':''}<a target="_blank" href="${url}">查看原文</a></div>`;for(let [cat,s] of fs){let z=need?await translate(s.slice(0,220)):s.slice(0,220);h+=`<div class="factrow"><b>${E(cat)}</b><div><p>${E(z)}</p></div></div>`}h+='</div>'}b.innerHTML=h}
window.overview=function(x){let r=rr(x);$('#hero').innerHTML=`<div class="hg"><div><div class="k">ANTDEX · ${E(x.f+' · '+(x.fz||SF[x.f]||''))} · ${x.p?'深度资料':'图鉴收录'}</div><h1>${E(lab(x))}</h1>${hz(x)?`<div class="latin">${E(x.s)}</div>`:''}${x.a.length?`<div class="alias">别名：${E(x.a.join(' / '))}</div>`:''}<div class="tax">Formicidae 蚁科 → ${E(x.f)} → ${E(x.g)} → <i>${E(x.s)}</i></div><div class="acts"><button class="dark" id="full">查看完整详情 →</button></div></div><div><div class="photo" id="pic"><div class="ph">正在匹配自然 / 生态照片…</div></div></div></div>`;$('#content').innerHTML=`<div class="grid"><div class="card"><h3>物种概览</h3><p>${E(r.summary||x.sm||'已进入 AntDex 图鉴收录层。当前优先保证中文名、分类骨架和来源入口；未核实的物种级参数暂不代填。')}</p></div><div class="card"><h3>分类与名称</h3><div class="meta"><b>亚科</b><span>${E(x.f+' · '+(x.fz||SF[x.f]||''))}</span><b>属</b><span>${E(x.g)}</span><b>中文名状态</b><span>${hz(x)?E(x.cn||'已有中文名'):'待补中文名'}</span><b>地区</b><span>${E(x.reg.join(' / ')||r.distribution||'待物种级核实')}</span></div></div><div class="card"><h3>体型</h3><div class="meta"><b>工蚁</b><span>${E(pv(x,'w'))}</span><b>蚁后</b><span>${E(pv(x,'q'))}</span></div></div><div class="card"><h3>饲养环境</h3><div class="meta"><b>温度</b><span>${E(pv(x,'t'))}</span><b>湿度/保湿</b><span>${E(pv(x,'hu'))}</span></div></div><div class="card"><h3>生境与巢址</h3><div class="meta"><b>生境</b><span>${E(x.hab||r.ecology||'待物种级核实')}</span><b>巢址</b><span>${E(x.ne||'待物种级核实')}</span></div></div><div class="card"><h3>食性</h3><p>${E(x.di||'待物种级核实')}</p></div><div class="card wide"><h3>来源</h3>${links(x)}</div></div>`;$('#full').onclick=()=>{mode=1;center();$('.center').scrollTo({top:0,behavior:'smooth'})};natural(x,'pic')}
window.full=function(x){$('#hero').innerHTML=`<div class="fullbar"><button class="ghost" id="back">← 返回物种概览</button><b>${E(lab(x))}</b><i>${E(x.s)}</i></div>`;$('#content').innerHTML=`<div class="grid"><div class="card"><h3>分类信息</h3><div class="meta"><b>学名</b><span><i>${E(x.s)}</i></span><b>属</b><span>${E(x.g)}</span><b>亚科</b><span>${E(x.f+' · '+(x.fz||SF[x.f]||''))}</span><b>等级</b><span>${E(x.r)}</span></div></div><div class="card"><h3>核心参数</h3><div class="meta"><b>工蚁</b><span id="coreWorker">${E(pv(x,'w'))}</span><b>蚁后</b><span id="coreQueen">${E(pv(x,'q'))}</span><b>温度</b><span>${E(pv(x,'t'))}</span><b>湿度</b><span>${E(pv(x,'hu'))}</span></div><div class="source-note">核心参数与详细资料现在使用同一套字段优先级。缺失体长时，只从物种级来源识别明确的 mm 总长；HL/HW/SL 等局部测量不会当作总体长。</div></div>${richCards(x)}<div class="card wide"><div class="photo" id="fp"><div class="ph">加载自然 / 生态照片…</div></div></div><div class="card wide" id="sourceDetail"><h3>公开来源资料整理</h3><p>正在读取……</p></div><div class="card wide"><h3>AntWeb 标准标本照</h3><p style="margin-bottom:10px">标本照只在完整详情页加载，用于 HEAD / PROFILE / DORSAL 形态观察。</p><div class="gallery" id="gal"><div class="empty">加载中…</div></div></div><div class="card wide"><h3>来源</h3>${links(x)}</div></div>`;$('#back').onclick=()=>{mode=0;center()};natural(x,'fp');sourceDetail2(x);antweb(x)}
list();center();
})();
